src/main/java/org/assertj/core/api/AbstractBigDecimalAssert.java

Enable to use this :
assertThat(new BigDecimal("8.0")).isNotEqualByComparingTo("7.99999999");
In addition to :
assertThat(new BigDecimal("8.0")).isNotEqualByComparingTo(new BigDecimal("7.99999999"));

 Add isNotEqualByComparingTo() in AbstractBigDecimalAssert.

---

README.md

The CloudBees build server for AssertJ appears to have been turned down but
there's an up-to-date Travis CI build is configured and running, so let's use
that.
This change adds per-branch build status images for `master`, `2.x`, and `1.x`.
To see how the new README looks, take a look at [my branch](https://github.com/mbrukman/assertj-core/tree/readme-build-status).

Fix build status: s/CloudBees/Travis CI/.

---

src/main/java/org/assertj/core/api/AbstractFileAssert.java

As far as I can tell https://github.com/joel-costigliola/assertj-core/issues/349 is now complete, at least for the 2.x branch. :smile:

add missing javadoc example to AbstractFileAssert

---

src/main/java/org/assertj/core/error/OptionalShouldContain.java
src/test/java/org/assertj/core/error/OptionalShouldContain_create_Test.java

When we are comparing Optional's content against something else and Optional turns out to be empty, we get:
`Expecting:
<Optional.empty>
to contain:
<10>
but did not."`
I made it reuse already defined error message for the empty Optional case:
`Expecting Optional to contain:
<10>
but was empty."`

Reuse empty Optional error message in other situations

---

src/main/java/org/assertj/core/api/IterableAssert.java
src/test/java/org/assertj/core/api/Assertions_assertThat_with_Iterator_Test.java

Make IterableAssert unroll the actual value for assertSame and assertNotSame

---

src/main/java/org/assertj/core/api/AbstractBDDSoftAssertions.java
src/main/java/org/assertj/core/api/AbstractStandardSoftAssertions.java
src/main/java/org/assertj/core/api/Assertions.java
src/main/java/org/assertj/core/api/AssertionsForClassTypes.java
src/main/java/org/assertj/core/api/AssertionsForInterfaceTypes.java
src/main/java/org/assertj/core/api/BDDAssertions.java
src/main/java/org/assertj/core/api/Java6AbstractBDDSoftAssertions.java
src/main/java/org/assertj/core/api/Java6AbstractStandardSoftAssertions.java
src/main/java/org/assertj/core/api/Java6Assertions.java
src/main/java/org/assertj/core/api/Java6BDDAssertions.java
src/main/java/org/assertj/core/util/CheckReturnValue.java

* Fixes #157
I've found [this](https://github.com/joel-costigliola/assertj-core/pull/436), dug into Findbugs code, and [apparently](https://github.com/findbugsproject/findbugs/blob/264ae7baf890d2b347d91805c90057062b5dcb1e/findbugs/src/java/edu/umd/cs/findbugs/detect/BuildCheckReturnAnnotationDatabase.java#L120), Findbugs handles **any** annotation with name `CheckReturnValue` in its return value usage check. So, if we supply our own annotation, we can avoid being dependent on `jsr305` package.
If you approve it, I'll search for other classes in assertJ where it's reasonable to put this annotation and also will backport to 2.x version as well.
I also checked it against my build of this branch, it totally works! See …

CheckReturnValue for assertThat statements for Findbugs

---

src/test/java/org/assertj/core/error/ShouldHaveSuppressedException_create_Test.java

While doing https://github.com/joel-costigliola/assertj-core/pull/759, this test was failing on my side (I am using Windows :)). This fixes the test (it makes sure that it uses `%s` instead of `\n`

Fix platform specific test

---

src/test/java/org/assertj/core/api/AbstractComparableAssertBaseTest.java
src/test/java/org/assertj/core/api/byte_/ByteAssert_isCloseToPercentage_primitive_byte_Test.java
src/test/java/org/assertj/core/api/byte_/ByteAssert_isCloseTo_byte_Test.java
src/test/java/org/assertj/core/api/byte_/ByteAssert_isCloseTo_primitive_byte_Test.java
src/test/java/org/assertj/core/api/byte_/ByteAssert_isNotCloseToPercentage_primitive_byte_Test.java
src/test/java/org/assertj/core/api/byte_/ByteAssert_isNotCloseTo_primitive_byte_Test.java
src/test/java/org/assertj/core/api/bytearray/ByteArrayAssert_containsOnlyOnce_with_Integer_Arguments_Test.java
src/test/java/org/assertj/core/api/bytearray/ByteArrayAssert_containsOnly_with_Integer_Arguments_Test.java
src/test/java/org/assertj/core/api/charsequence/CharSequenceAssert_containsSequence_with_var_args_Test.java
src/test/java/org/assertj/core/api/charsequence/CharSequenceAssert_hasLineCount_Test.java
src/test/java/org/assertj/core/api/charsequence/CharSequenceAssert_isBlank_Test.java
src/test/java/org/assertj/core/api/charsequence/CharSequenceAssert_isJavaBlank_Test.java
src/test/java/org/assertj/core/api/charsequence/CharSequenceAssert_isNotBlank_Test.java
src/test/java/org/assertj/core/api/charsequence/CharSequenceAssert_isNotJavaBlank_Test.java
src/test/java/org/assertj/core/api/comparable/AbstractComparableAssert_isBetween_Test.java
src/test/java/org/assertj/core/api/comparable/AbstractComparableAssert_isStrictlyBetween_Test.java
src/test/java/org/assertj/core/api/comparable/AbstractComparableAssert_usingComparator_Test.java
src/test/java/org/assertj/core/api/comparable/AbstractComparableAssert_usingDefaultComparator_Test.java
src/test/java/org/assertj/core/api/long_/LongAssert_isCloseToPercentage_primitive_long_Test.java
src/test/java/org/assertj/core/api/long_/LongAssert_isCloseTo_primitive_long_Test.java
src/test/java/org/assertj/core/api/long_/LongAssert_isNotCloseToPercentage_primitive_long_Test.java
src/test/java/org/assertj/core/api/long_/LongAssert_isNotCloseTo_primitive_long_Test.java
src/test/java/org/assertj/core/api/map/MapAssert_hasEntrySatisfying_Test.java
src/test/java/org/assertj/core/api/objectarray/ObjectArrayAssert_containsSubSequence_Test.java

I've been playing a bit with [pitest](http://pitest.org/) and I saw that there are some tests which were missing.
@joel-costigliola, if you are interested I can setup a maven profile that will allow anyone to run pitest analysis over AssertJ.

Add missing tests for various classes

---

src/main/java/org/assertj/core/api/AbstractObjectArrayAssert.java
src/main/java/org/assertj/core/api/ObjectEnumerableAssert.java

Fix misspelling of Arya Stark in JavaDoc examples (fixes #779).

---

src/main/java/org/assertj/core/api/SoftAssertions.java
src/test/java/org/assertj/core/api/SoftAssertionsTest.java

This makes SoftAssertions a bit nicer to use since you can simply accept the instance in a lamda function instead of having to assign it and then call assertAll() at the end.
* Fixes: convenience method for making it easier to use SoftAssertions
* Unit tests : YES, SoftAssertionsTest.should_assert_using_assertSoftly

add static assertSoftly method

---

pom.xml
src/test/java/org/assertj/core/util/Throwables_getStackTrace_Test.java

just to demonstrate that it works with just a minimal change (removed wildcard imports because compiler complains that `isA` is ambiguous
real pull request is https://github.com/joel-costigliola/assertj-maven-parent-pom/pull/16

mockito-core version to 2.2.9

---

src/test/java/org/assertj/core/internal/iterables/Iterables_assertAllSatisfy_Test.java
src/test/java/org/assertj/core/internal/maps/Maps_assertHasEntrySatisfyingConsumer_Test.java

Eclipse (tested in Oxygen) compiler fails to compile some test because of type inference. 
This fix those compile error.

Fixed two compile error with Eclipse Compiler.

---

src/test/java/org/assertj/core/api/abstract_/AbstractAssert_withRepresentation_Test.java
src/test/java/org/assertj/core/api/array/AbstractEnumerableAssert_hasSameSizeAs_with_Array_Test.java
src/test/java/org/assertj/core/api/date/DateAssert_setLenientDateParsing.java
src/test/java/org/assertj/core/api/filter/AbstractTest_equals_filter.java
src/test/java/org/assertj/core/api/filter/Filter_with_property_in_given_values_Test.java
src/test/java/org/assertj/core/api/filter/Filter_with_property_not_equals_to_given_value_Test.java
src/test/java/org/assertj/core/api/filter/Filter_with_property_not_in_given_values_Test.java
src/test/java/org/assertj/core/api/iterable/IterableAssert_filteredOnNull_Test.java
src/test/java/org/assertj/core/api/iterable/IterableAssert_filteredOn_Test.java
src/test/java/org/assertj/core/api/iterable/IterableAssert_filteredOn_in_Test.java
src/test/java/org/assertj/core/api/iterable/IterableAssert_filteredOn_notIn_Test.java
src/test/java/org/assertj/core/api/iterable/IterableAssert_filteredOn_not_Test.java
src/test/java/org/assertj/core/api/objectarray/ObjectArrayAssert_filteredOn_Test.java
src/test/java/org/assertj/core/api/objectarray/ObjectArrayAssert_filteredOn_in_Test.java
src/test/java/org/assertj/core/api/objectarray/ObjectArrayAssert_filteredOn_notIn_Test.java
src/test/java/org/assertj/core/api/objectarray/ObjectArrayAssert_filteredOn_not_Test.java
src/test/java/org/assertj/core/internal/objects/Objects_assertIsEqualToComparingOnlyGivenFields_Test.java
src/test/java/org/assertj/core/internal/objects/Objects_assertIsEqualToIgnoringNullFields_Test.java
src/test/java/org/assertj/core/test/ExpectedException.java

There are many more tests which could be updated to use `ExpectedException`, but maybe we should rather wait till assertj is java 8 only and use `assertThatThrownBy`?

increase ExpectedException usage

---

src/main/java/org/assertj/core/util/diff/Chunk.java
src/main/java/org/assertj/core/util/diff/Delta.java
src/main/java/org/assertj/core/util/diff/DiffAlgorithm.java
src/main/java/org/assertj/core/util/diff/DiffUtils.java
src/main/java/org/assertj/core/util/diff/myers/MyersDiff.java

This change breaks binary compatibility if somebody uses these classes and there methods/constructors directly, so feel free to reject.

remove unused methods and constructors in diff package

---

src/main/java/org/assertj/core/api/IterableAssert.java
src/main/java/org/assertj/core/api/ListAssert.java

* Unit tests : NA (Methods were already covered)
`IterableAssert` and `ListAssert` are missing a few overrides of varargs methods. Without those overrides, consumers get warnings about unchecked operations.

Added missing @SafeVarargs overrides

---

src/main/java/org/assertj/core/api/Assertions.java
src/test/java/org/assertj/core/api/Assertions_assertThatExceptionOfType_Test.java

Hello,
I've pushed some short cut method for "common" exception such as NullPointerException: I though it was rather sad to always write something like:
```
assertThatExceptionOfType(NullPointerException.class)
.isThrownBy(() -> file.save((Path) null)).withMessage("path");
```
While it could be:
```
assertThatNullPointerException().isThrownBy(() -> file.save((Path) null)).withMessage("path");
```
I did not add API example as there are purely alias to existing methods (eg: `assertThatExceptionOfType(NullPointerException.class)`).

Added shortcut for assertThatExceptionOfType to exception:

---

pom.xml

The JUnit dependency of assertj-core is mark as provided but not as optional. The unfortunate consequence is that integration tests using AssertJ requires to have a dependency towards JUnit even if you're not using it at all and using another test framework (TestNG for instance). Since it's not marked as optional, any OSGi framework will refuse to start because it misses the JUnit packages.
Marking this dependency as optional will allow running integration tests using OSGi and TestNG.

Mark JUnit dependency of assertj-core as optional

---

src/test/java/org/assertj/core/api/WithAssertions_delegation_Test.java

In addition to #899 the master only one.

Long literal ending with 'l' instead of 'L' (master only)

---

src/main/java/org/assertj/core/api/AbstractBigIntegerAssert.java
src/main/java/org/assertj/core/api/AtomicBooleanAssert.java

- using meaningful generic names in `AbstractBigIntegerAssert`
- get rid of `//TODO add to WithAssertions in 3.x` since `AtomicBooleanAssert` is already added to `WithAssertions` in 3.x

meaningful generic names  + get rid of TODO

---

pom.xml

Add java9 maven profile which is enable on java 9. This profile open up some packages of the java.base module for access via reflection in order to fix test failures on java 9.

Java 9 reflection changes (#928)

---

README.md

No ideal, as there seems to be no way to include branch information in  a travis badge, but the available space is put to better use.
For a test library the license is probably not that important, but it is still nice to know that assertj is apache licensed.
What do you think?

add license badge and reorganize badges

---

src/main/java/org/assertj/core/groups/Tuple.java
src/test/java/org/assertj/core/api/Tuple_Test.java

What about getting rid of deprecated Tuple#addData?
It is not used by the assertj-core project and seems to be deprecated for > 1.5 years now.

get rid of deprecated Tuple#addData

---

pom.xml
src/main/java/org/assertj/core/api/HamcrestCondition.java
src/test/java/org/assertj/core/api/HamcrestConditionTest.java

I think the result is impressive for so little effort.
Error messages are surprisingly readable:
> java.lang.AssertionError: 
> Expecting:
> <"bc">
> to be <a string containing "a">

Support Hamcrest matchers as conditions (#556)

---

src/main/java/org/assertj/core/api/Assertions.java
src/main/java/org/assertj/core/api/Assumptions.java
src/main/java/org/assertj/core/api/HamcrestCondition.java
src/main/java/org/assertj/core/configuration/ConfigurationProvider.java
src/main/java/org/assertj/core/presentation/Representation.java

This is some small Javadoc changes and cleanups:
* Add some missing since tags
* Make the ConfigurationProvider constructor private
* Do some rewording and fix some typos around the new SPI Representation
I think that the most important change here is that the `META-INF/services` folder needs to be in `src/test/resources` and not `src/main/resources`. Users usually have a test scoped dependency of AssertJ.
I've also fixed some small typos that I saw and I added the recommended way of writing a custom `Representation`. I think it is much easier for the users if they just extend the `StandardRepresentation` and override `fallbackToStringOf(Object)` method, this way they won't mess with all the defaults from AssertJ.

Small cleanups

---

.travis.yml
src/main/java/org/assertj/core/api/AbstractSoftAssertions.java
src/test/java/org/assertj/core/util/xml/XmlStringPrettyFormatter_prettyFormat_Test.java

Filtering the "jdk.internal.reflect" classes from the stacktraces is required to fix SoftAssertion error messages. Otherwise e.g. using SoftAssertions#fail will display an ugly error message (see below):
```
[ERROR]   SoftAssertionsTest.should_return_failure_after_fail
Expecting message:
<"Should not reach here">
but was:
<"Should not reach here
at NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)">
```

Add java 9 to master build

---

src/main/java/org/assertj/core/api/AbstractIterableAssert.java
src/main/java/org/assertj/core/api/AbstractObjectArrayAssert.java
src/main/java/org/assertj/core/api/AtomicReferenceArrayAssert.java
src/main/java/org/assertj/core/api/ObjectEnumerableAssert.java
src/main/java/org/assertj/core/internal/Arrays.java
src/main/java/org/assertj/core/internal/Iterables.java
src/main/java/org/assertj/core/internal/ObjectArrays.java
src/main/java/org/assertj/core/util/Arrays.java
src/test/java/org/assertj/core/api/atomic/referencearray/AtomicReferenceArrayAssert_endsWith_Test.java
src/test/java/org/assertj/core/api/iterable/IterableAssert_endsWith_Test.java
src/test/java/org/assertj/core/api/objectarray/ObjectArrayAssert_endsWith_Test.java
src/test/java/org/assertj/core/internal/booleanarrays/BooleanArrays_assertEndsWith_Test.java
src/test/java/org/assertj/core/internal/bytearrays/ByteArrays_assertEndsWith_Test.java
src/test/java/org/assertj/core/internal/bytearrays/ByteArrays_assertEndsWith_with_Integer_Arguments_Test.java
src/test/java/org/assertj/core/internal/chararrays/CharArrays_assertEndsWith_Test.java
src/test/java/org/assertj/core/internal/doublearrays/DoubleArrays_assertEndsWith_Test.java
src/test/java/org/assertj/core/internal/floatarrays/FloatArrays_assertEndsWith_Test.java
src/test/java/org/assertj/core/internal/intarrays/IntArrays_assertEndsWith_Test.java
src/test/java/org/assertj/core/internal/iterables/Iterables_assertEndsWith_Test.java
src/test/java/org/assertj/core/internal/longarrays/LongArrays_assertEndsWith_Test.java
src/test/java/org/assertj/core/internal/objectarrays/ObjectArrays_assertEndsWith_Test.java
src/test/java/org/assertj/core/internal/shortarrays/ShortArrays_assertEndsWith_Test.java

The new `endsWith(T[])` allows empty arrays whereas the former
`endsWith(T...)` has been changed to `endsWith(T, T...)` to
explicitly prevent empty varargs.
* Fixes #1052

Fixes #1052 by overloading endsWith assertion

---

src/main/java/org/assertj/core/api/SoftAssertionPredicateAssert.java

While fiddling with the proxies I noticed that the `SoftAssertionPredicate` has wrong class in it's extends clause

Use correct SELF class for SoftAssertionPredicateAssert

---

src/main/java/org/assertj/core/api/AbstractObjectAssert.java

Remove a source of confusion when reading the docs.

Fix `isEqualTo` typo.

---

src/main/java/org/assertj/core/api/AbstractAssert.java
src/test/java/org/assertj/core/api/abstract_/AbstractAssert_equal_hashCode_Test.java

Make configurable if AbstractAssert#equals throws an exception

---

.travis.yml

Currently the javadoc is in pristine state (no warnings or errors). 😄 
Let's make sure it stays that way and let travis create javadoc so javadoc errors of pull requests are detected early on.
What do you think?

.travis.yml: run javadoc:javadoc to detect javadoc errors

---

pom.xml

No idea why we had this dependency (as we were using cg-lib-nodep with embeds ASM).
Byte-Buddy also embeds AMS, so this should be necessary. If it is for some reason, we should update to 6.0 because this is the version used by Byte-Buddy.

remove unnecessary optional ASM dependency

---

README.md

-You can ask questions [**stackoverflow (assertj tag)**] -> You can ask questions in [**stackoverflow (assertj tag)**]
-The idea is that, when writing unit tests, we should have at our disposal assertions specific to the type of the objects we are checking -> The idea is that disposal assertions should be specific to the type of the objects we are checking when writing unit tests
-Use Map-specific assertions, which make it easy to check the contents of the map -> Use Map-specific assertions to easily check the contents of the map
-AssertJ's assertions read very close to plain English -> AssertJ's assertions are very close to plain English
-you might want some that are specific to your own types -> you might want some assertions specific to your own types
-This is possible with AssertJ …

Rewriting README.md to make it more technical and clear

---

src/main/java/org/assertj/core/api/ListAssert.java

Streams may carry resources which require closing such as
java.nio.file.Files#lines(java.nio.file.Path).
* Fixes #1217 

Fix #1217: Close stream after materialisation in ListAssert

---

src/main/java/org/assertj/core/api/Assumptions.java
src/main/java/org/assertj/core/api/SoftProxies.java

I did some more benchmarking and reading annotations is a really expensive operation compared to anything else. Since the delegators read annotations, the repeated reading can be avoided by caching these delegators.

Reuse delegation instances

---

src/main/java/org/assertj/core/api/AbstractSoftAssertions.java

This is a suggestion of how to avoid error list modification for those who doesn't want it, and still retain this functionality for those who do. I am not sure about method names but this is the general idea anyway.
* Fixes #1036

Allow overriding collected error list modification

---

src/main/java/org/assertj/core/api/Assertions.java
src/main/java/org/assertj/core/api/AssertionsForClassTypes.java
src/main/java/org/assertj/core/api/Assumptions.java
src/main/java/org/assertj/core/api/BDDAssertions.java
src/main/java/org/assertj/core/api/Java6AbstractBDDSoftAssertions.java
src/main/java/org/assertj/core/api/Java6AbstractStandardSoftAssertions.java
src/main/java/org/assertj/core/api/Java6Assertions.java
src/main/java/org/assertj/core/api/Java6BDDAssertions.java
src/main/java/org/assertj/core/api/WithAssertions.java
src/main/java/org/assertj/core/api/WithAssumptions.java
src/test/java/org/assertj/core/api/Assertions_assertThat_with_StringBuffer_Test.java
src/test/java/org/assertj/core/api/Assertions_assertThat_with_StringBuilder_Test.java

* Fixes  #1232
* Unit tests : YES / NO / NA
* Javadoc with a code example (API only) : YES / NO / NA
Should we add some additional test too or are we fine with the ones we are having in place?
Additionally, should we merge  #1234 first and I do a rebase afterwards and make a change to no longer allow failing java11 builds?

java11 compatibility

---

src/main/java/org/assertj/core/api/Assertions.java
src/main/java/org/assertj/core/api/AssertionsForClassTypes.java
src/main/java/org/assertj/core/api/BDDAssertions.java
src/main/java/org/assertj/core/api/Java6AbstractBDDSoftAssertions.java
src/main/java/org/assertj/core/api/Java6AbstractStandardSoftAssertions.java
src/main/java/org/assertj/core/api/Java6Assertions.java
src/main/java/org/assertj/core/api/Java6BDDAssertions.java

…that an exception has been thrown (fixes #1268).

Remove @CheckReturnValue from #assertThatThrownBy and #thenThrownBy, because these method check that an exception has been thrown.

---

pom.xml

* Fixes #1290
Added org.junit, org.opentest4j and org.testng as optional imports to the OSGi Import-Package manifest entry. This allows `org.assertj.core.api.Assumptions.getAssumptionClass()` to resolve these classes if their bundles are installed in the current environment - without these import statements, they won't load and the assumption will throw an `IllegalStateException`.
Proper regression testing would be nice, but requires a full-blown OSGi integration test which does not exist yet.

Add test packages as optional imports to OSGi manifest

---

pom.xml
src/main/java/org/assertj/core/api/Assertions.java
src/main/java/org/assertj/core/util/CanIgnoreReturnValue.java

... by using `CanIgnoreReturnValue` for `Assertions.fail*`
* Fixes #1298
* Javadoc with a code example (API only) :  NA
This pr is based on #1299

Fixes problems caused by @CheckReturnValue 

---

src/main/java/org/assertj/core/internal/Strings.java
src/test/java/org/assertj/core/internal/strings/Strings_assertEqualsIgnoringWhitespace_Test.java
src/test/java/org/assertj/core/internal/strings/Strings_assertIsEqualToNormalizingNewlines_Test.java
src/test/java/org/assertj/core/internal/strings/Strings_assertIsEqualsToIgnoringNewLines_Test.java

Throw AssertionFailedError instead in non-strict string assertions

---

src/main/java/org/assertj/core/api/SoftProxies.java

I am working on JsonUnit AssertJ integration. I'd like to add support for soft assertions. My class JsonAssert calls 'useComparator' in the constructor. Since the method is proxied, intercept is called before errorCollector setup and it ends-up in NPE. I can change the behavior or JsonAssert, but I assume that this is better solution.

Do not proxy 'useComparator' method

---

src/main/java/org/assertj/core/util/DoubleComparator.java
src/main/java/org/assertj/core/util/FloatComparator.java
src/test/java/org/assertj/core/util/DoubleComparatorTest.java
src/test/java/org/assertj/core/util/FloatComparatorTest.java

Now floating point numbers with the same infinite values will be
considered equals by default.
* Fixes: https://github.com/joel-costigliola/assertj-core/issues/1390

Issue-1390 Double and Float comparator support Infinity

---

src/main/java/org/assertj/core/api/AbstractMapAssert.java
src/main/java/org/assertj/core/api/AbstractThrowableAssert.java

I thought it might be good to add missing since for assertj 3.12.0.
I can link the corresponding pr's if that makes it easier to review (but maybe git annotate is easier to use).

Add missing @since

---

pom.xml

see [release notes](https://github.com/raphw/byte-buddy/blob/master/release-notes.md#4-february-2019-version-199) for details

Update byte-buddy to version 1.9.9

---

pom.xml
src/main/java/org/assertj/core/api/AbstractObjectAssert.java
src/main/java/org/assertj/core/api/RecursiveComparisonAssert.java
src/main/java/org/assertj/core/api/recursive/comparison/RecursiveComparisonConfiguration.java

@joel-costigliola It took me a while to figure it out, but I think the nested list error is not a bug in Javadoc. The usage of list tags was actually "incorrect" (browsers do not care, but Javadoc is more strict).
With the change below the error disappeared when using Javadoc on Java 11.0.1.

Fix javadoc and reenable Javadoc doclint verification

---

src/main/java/org/assertj/core/api/AbstractStringAssert.java
src/test/java/org/assertj/core/api/string_/StringAssert_isEqualTo_Test.java

let's fail with a proper error message if the given 'expectedStringTemplate' is null.
note: this one is not the same as in #1440

Fail with error message if the given expectedStringTemplate is null

---

README.md

@joel-costigliola it looks like we have to use `org.assertj` instead of `joel-costigliola` for both, the badge and the link, isn't it?

adjust javadoc badge

---

src/main/java/org/assertj/core/api/Assertions.java
src/main/java/org/assertj/core/api/Java6Assertions.java
src/main/java/org/assertj/core/api/WithAssertions.java
src/main/java/org/assertj/core/condition/AllOf.java

* Fixes some mixing up between the two types `AnyOf` and `AllOf`.

Fix JavaDoc regarding `AnyOf` and `AllOf`

---

src/main/java/org/assertj/core/api/AbstractDoubleAssert.java
src/main/java/org/assertj/core/api/AbstractFloatAssert.java

see e.g. [Double java doc](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Double.html#%3Cinit%3E(double)) for details.

Get rid of deprecated Double and Float constructor usage

---

src/main/java/org/assertj/core/api/AbstractMapAssert.java
src/main/java/org/assertj/core/api/AbstractObjectAssert.java

Trivial: adding missing `@since` for the methods introduced in #1469.

Add missing @since for single parameter 'extracting'

---

src/main/java/org/assertj/core/api/RecursiveComparisonAssert.java
src/main/java/org/assertj/core/api/recursive/comparison/RecursiveComparisonConfiguration.java
src/main/java/org/assertj/core/api/recursive/comparison/RecursiveComparisonDifferenceCalculator.java
src/test/java/org/assertj/core/api/recursive/comparison/RecursiveComparisonAssert_fluent_API_Test.java
src/test/java/org/assertj/core/api/recursive/comparison/RecursiveComparisonAssert_isEqualTo_ignoringCollectionOrderInFields_Test.java
src/test/java/org/assertj/core/api/recursive/comparison/RecursiveComparisonAssert_isEqualTo_ignoringCollectionOrder_Test.java
src/test/java/org/assertj/core/api/recursive/comparison/RecursiveComparisonConfiguration_multiLineDescription_Test.java
src/test/java/org/assertj/core/api/recursive/comparison/RecursiveComparisonConfiguration_shouldIgnoreCollectionOrder_Test.java
src/test/java/org/assertj/core/internal/objects/data/FriendlyPerson.java

Add ignoringCollectionOrderInFields() and ignoringCollectionOrderInFieldsMatchingRegexes() to Recursive API.
* Fixes #1494

Add ignoring collection order to Recursive API

---

src/main/java/org/assertj/core/api/Assert.java

Fix typo in Assert's javadoc

---

src/main/java/org/assertj/core/api/InstanceOfAssertFactories.java
src/test/java/org/assertj/core/api/Assertions_sync_with_InstanceOfAssertFactories_Test.java
src/test/java/org/assertj/core/api/InstanceOfAssertFactoriesTest.java

Sync test for `InstanceOfAssertFactories` (follows #1498).
Adds also missing factories (spotted by the test, yay!) for `StringBuilder` and `StringBuffer` and a `type(Class)` factory to obtain an `ObjectAssert` with updated type.

Add sync test between Assertions and InstanceOfAssertFactories

---

.travis.yml
src/test/java/org/assertj/core/internal/paths/MockPathsBaseTest.java

I do not know if we should keep https://github.com/joel-costigliola/assertj-core/pull/1531/commits/eea3712e4aa0f0237a0c3dab1d1757d6707feec2
No idea if this is bug in the first Java 14 EA build or a deliberate change in Java 14 (that may require changes in mockito).

Travis CI: Add Java 13 build and restore Java EA build

---

src/main/java/org/assertj/core/api/WithAssertions.java

Allow return values of WithAssertions#fail methods to be ignored

---

LICENSE

This should allow GitHub to dislay the nicer Apache-2.0 license title like in [assertj/doc](https://github.com/assertj/doc/tree/master).

Adjust LICENSE to make it GitHub friendly

---

pom.xml

Exclude assertj-core from junit-platform-testkit

---

src/main/java/org/assertj/core/api/AbstractObjectAssert.java
src/main/java/org/assertj/core/api/ProxyableObjectAssert.java
src/test/java/org/assertj/core/api/abstract_/AbstractAssert_asInstanceOf_with_instanceOfAssertFactory_Test.java
src/test/java/org/assertj/core/api/object/ObjectAssert_extracting_with_function_Test.java
src/test/java/org/assertj/core/api/object/ObjectAssert_extracting_with_function_array_Test.java

In case of `extracting(Function)`, the type parameter of the resulting `ObjectAssert` can be inferred from the input `Function`, allowing then to chain other type aware methods (e.g., additional `extracting`).
```java
Person yoda = new Person("Yoda");
// Old implementation
assertThat(yoda)
.extracting(Jedi::getName) // ObjectAssert<Object>
.extracting(String::length) // Not compiling
.isEqualTo(4);
// New implementation
assertThat(yoda)
.extracting(Jedi::getName) // ObjectAssert<String>
.extracting(String::length)  // Compiling!
.isEqualTo(4);
```
While the implementation changes are trivial, I used the occasion for some test refactoring.
* Fixes NA
* Javadoc with a code example (API only) : YES (already existing)

Propagate value type with extracting(Function)

---

src/test/java/org/assertj/core/api/junit/jupiter/AbstractSoftAssertionsExtensionIntegrationTests.java
src/test/java/org/assertj/core/api/junit/jupiter/BDDSoftAssertionsExtensionIntegrationTest.java
src/test/java/org/assertj/core/api/junit/jupiter/SoftAssertionsExtensionIntegrationTest.java
src/test/java/org/assertj/core/api/junit/jupiter/SoftAssertionsExtensionUnitTest.java

Prior to this commit, the example test cases used to test the `SoftAssertionsExtension` were properly excluded from the Maven build by intentionally not following the "*Test" naming convention; however, those test cases were executed within IDEs, resulting in failures.
This commit addresses this inconvenience by annotating all example test cases with `@Disabled` and deactivating the `DisabledCondition` when actually executing the test cases via the `EngineTestKit`.
See #1418

Disable example test cases for SoftAssertionsExtension

---

src/main/java/org/assertj/core/api/AbstractIterableAssert.java

* Fixes javadoc
* Unit tests: NA

typo in javadoc

---

src/main/java/org/assertj/core/error/AssertionErrorCreator.java

Make dependency on OpenTest4J optional again (fixes #1563).

---

pom.xml

The maven build under JDK 8 fails because of the unsupported `release` parameter, which is indeed only supported [since java 9](https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#release).
As the right value is already specified in the `java9+` maven profile, I think the `release` parameter should be removed from the base configuration.

Remove release parameter from maven-compiler-plugin base configuration

---

src/main/scripts/convert-junit-assertions-to-assertj.sh

When executing the conversion script on Windows (in the bash shell of Git for Windows) it stops with an error:
`./convert-junit-assertions-to-assertj.sh: line 45: `replace-in-all-files': not a valid identifier`
Shortening the function name to not contain hyphen characters fixes the problem.
* Fixes #1654

Fix #1654: Make conversion script work on Windows

---

pom.xml

Fixes https://github.com/joel-costigliola/assertj-core/issues/1663

Make OSGi import of jdk.* packages optional

---

src/main/java/org/assertj/core/error/ShouldHaveSizeGreaterThan.java
src/main/java/org/assertj/core/error/ShouldHaveSizeGreaterThanOrEqualTo.java
src/main/java/org/assertj/core/error/ShouldHaveSizeLessThan.java
src/test/java/org/assertj/core/error/ShouldHaveSizeGreaterThanOrEqualTo_create_Test.java
src/test/java/org/assertj/core/error/ShouldHaveSizeGreaterThan_create_Test.java
src/test/java/org/assertj/core/error/ShouldHaveSizeLessThanOrEqualTo_create_Test.java
src/test/java/org/assertj/core/error/ShouldHaveSizeLessThan_create_Test.java

I've enabled errorprone locally and found the following violation:
`[FormatString] extra format arguments: used 2, provided 3`

get rid of not needed extra arguments (String.format)

---

src/main/java/org/assertj/core/api/AbstractObjectAssert.java

* Removes unmeaningful whitespace in javadoc.

Fix typo in javadoc

---

src/main/java/org/assertj/core/internal/Uris.java
src/test/java/org/assertj/core/internal/UrisBaseTest.java
src/test/java/org/assertj/core/internal/urls/Uris_getParameters_Test.java

The method was public only to allow access from tests. This refactoring
still allows the access but without having it public.

Reduce visibility of getParameters()

---

src/main/java/org/assertj/core/api/AbstractMapAssert.java
src/test/java/org/assertj/core/api/map/MapAssert_containsOnlyKeys_with_Path_Test.java

Do no treat Path as Iterable in MapAssert#containsOnlyKeys(Iterable)

---

src/main/java/org/assertj/core/api/AbstractClassAssert.java
src/main/java/org/assertj/core/error/ShouldHaveNoSuperclass.java
src/main/java/org/assertj/core/error/ShouldHaveSuperclass.java
src/main/java/org/assertj/core/internal/Classes.java
src/test/java/org/assertj/core/api/classes/ClassAssert_hasNoSuperclass_Test.java
src/test/java/org/assertj/core/error/ShouldHaveNoSuperclass_create_Test.java
src/test/java/org/assertj/core/error/ShouldHaveSuperclass_create_Test.java
src/test/java/org/assertj/core/internal/classes/Classes_assertHasNoSuperclass_Test.java
src/test/java/org/assertj/core/internal/classes/Classes_assertHasSuperclass_Test.java

Main behavior change: `hasSuperclass(Class<?>)` now fails with `null` parameter.
* Fixes https://github.com/joel-costigliola/assertj-core/pull/1743#discussion_r362622859

Add hasNoSuperclass() to AbstractClassAssert

---

src/main/java/org/assertj/core/util/introspection/PropertyOrFieldSupport.java
src/test/java/org/assertj/core/util/introspection/PropertyOrFieldSupport_getSimpleValue_with_Map_input_Test.java

Try map input as last attempt in PropertyOrFieldSupport

---

src/main/java/org/assertj/core/api/recursive/comparison/ComparisonDifference.java
src/main/java/org/assertj/core/api/recursive/comparison/RecursiveComparisonDifferenceCalculator.java
src/main/java/org/assertj/core/error/ShouldBeEqual.java
src/main/java/org/assertj/core/error/ShouldBeEqualByComparingFieldByFieldRecursively.java
src/main/java/org/assertj/core/error/ShouldHaveCause.java
src/main/java/org/assertj/core/error/ShouldHaveRootCause.java
src/main/java/org/assertj/core/internal/Files.java
src/main/java/org/assertj/core/internal/Numbers.java
src/main/java/org/assertj/core/internal/Throwables.java
src/main/java/org/assertj/core/internal/Uris.java
src/main/java/org/assertj/core/internal/Urls.java
src/main/java/org/assertj/core/util/Objects.java

The wish would be to drop `org.assertj.core.util.Objects.areEqual()` in favor of `java.util.Objects.equals()` but it cannot be done in one take as `areEqual()` also does deep comparison for arrays.
This PR replaces `areEqual()` only where the type is well known at compile time (i.e., not `Object`).

Reduce areEqual() usage in favor of java.util.Objects.equals()

---

.github/workflows/main.yml

This workflow requires a `SONAR_TOKEN` secret.

Add Sonar scan on push events

---

pom.xml
src/main/java/org/assertj/core/groups/Tuple.java
src/main/java/org/assertj/core/internal/ExtendedByTypesComparator.java
src/main/java/org/assertj/core/internal/StandardComparisonStrategy.java
src/main/java/org/assertj/core/util/Objects.java
src/test/java/org/assertj/core/api/Tuple_Test.java
src/test/java/org/assertj/core/internal/objects/Objects_assertEqual_Test.java

Following #1764, this PR deprecates and reduces a bit more the usage of `areEqual()` and `areEqualArrays()`. Also it shows how an `EqualsVerifier` test would look like.

Deprecate areEqual() and areEqualArrays(), introduce EqualsVerifier

---

src/main/java/org/assertj/core/api/AbstractAssert.java
src/main/java/org/assertj/core/api/AbstractObjectAssert.java
src/test/java/org/assertj/core/api/NavigationMethodBaseTest.java
src/test/java/org/assertj/core/api/abstract_/AbstractAssert_asInstanceOf_with_InstanceOfAssertFactory_Test.java
src/test/java/org/assertj/core/api/abstract_/AbstractAssert_extracting_with_Function_and_AssertFactory_Test.java
src/test/java/org/assertj/core/api/abstract_/AbstractAssert_extracting_with_String_and_AssertFactory_Test.java
src/test/java/org/assertj/core/api/map/MapAssert_extractingByKey_with_Key_Test.java
src/test/java/org/assertj/core/api/map/MapAssert_extractingByKey_with_Key_and_InstanceOfAssertFactory_Test.java
src/test/java/org/assertj/core/api/map/MapAssert_extractingByKeys_Test.java
src/test/java/org/assertj/core/api/object/ObjectAssert_extracting_with_Function_and_InstanceOfAssertFactory_Test.java
src/test/java/org/assertj/core/api/object/ObjectAssert_extracting_with_String_and_InstanceOfAssertFactory_Test.java
src/test/java/org/assertj/core/api/optional/OptionalAssert_get_Test.java
src/test/java/org/assertj/core/api/optional/OptionalAssert_get_with_InstanceOfAssertFactory_Test.java

The PR is not ready yet, tests and javadoc need some reworking.
@kriegfrj @bjhargrave would this help your needs?
@joel-costigliola I added the `isPublic()` matcher to `METHODS_CHANGING_THE_OBJECT_UNDER_TEST` in `SoftProxies` to allow a protected `extracting` without changing the method name. At the moment I don't see any side effect but please let me know your opinion about it. ✅  Applied in 353484157d2b308950f36c0e48440f4d91ede45f.
* Fixes #1731

Add protected extracting to AbstractAssert

---

src/main/java/org/assertj/core/api/AbstractAssert.java
src/test/java/org/assertj/core/api/abstract_/AbstractAssert_satisfiesAnyOf_Test.java
src/test/java/org/assertj/core/data/TolkienCharacter.java

In a recent project this was necessary/useful and since there was no particular reason not to support it other than a missing use case, this seemed a good reason to support it from now on.
Fixes : NA
Unit tests : YES
Javadoc with a code example (on API only) : YES

Support four arguments for satisfiesAnyOf()

---

src/main/java/org/assertj/core/api/AbstractStringAssert.java
src/main/java/org/assertj/core/error/ShouldBeValidBase64.java
src/main/java/org/assertj/core/internal/Strings.java
src/test/java/org/assertj/core/api/StringAssertBaseTest.java
src/test/java/org/assertj/core/api/string_/StringAssert_isValidBase64_Test.java
src/test/java/org/assertj/core/error/ShouldBeValidBase64_create_Test.java
src/test/java/org/assertj/core/internal/StringsBaseTest.java
src/test/java/org/assertj/core/internal/strings/Strings_assertIsValidBase64_Test.java

Add isValidBase64 to AbstractStringAssert

---

src/main/java/org/assertj/core/api/AbstractStringAssert.java
src/main/java/org/assertj/core/api/SoftProxies.java
src/main/java/org/assertj/core/error/ShouldBeEqual.java
src/test/java/org/assertj/core/api/SoftAssertionsTest.java
src/test/java/org/assertj/core/api/string_/StringAssert_decodedAsBase64_Test.java

Add decodedAsBase64 to AbstractStringAssert

---

src/test/java/org/example/test/CustomSoftAssertionsLineNumberTest.java

Enable CustomSoftAssertionsLineNumberTest on non-MacOs operating systems

---

src/main/java/org/assertj/core/api/AbstractByteArrayAssert.java
src/main/java/org/assertj/core/api/SoftProxies.java
src/test/java/org/assertj/core/api/SoftAssertionsTest.java
src/test/java/org/assertj/core/api/bytearray/ByteArrayAssert_encodedAsBase64_Test.java

Add encodedAsBase64 to AbstractByteArrayAssert

---

src/main/java/org/assertj/core/util/Files.java

* Fixes #1289
The annotation @deprecated is added before the method  `File temporaryFolder()`. Also, the alternatives in JUnit4+JUnit5 are added in javadoc part of the method.

Fix issue #1289 by adding the annotation @deprecated to method temporaryFolder

---

pom.xml

This ensures that the html tag always contains language "en" and therefore does not default to the local used locale.
In order to verify that it works I've change the value to `de_DE` locally and the html tag did contain the de one afterwards.
* Fixes #1825
* Unit tests : YES / NO / **NA**
* Javadoc with a code example (on API only) : YES / NO / **NA**

Explicitly set Javadoc locale to English

---

src/main/java/org/assertj/core/api/AbstractUrlAssert.java
src/main/java/org/assertj/core/internal/Urls.java
src/test/java/org/assertj/core/api/uri/UriAssert_hasNoPath_Test.java
src/test/java/org/assertj/core/api/url/UrlAssert_hasNoPath_Test.java

* Fixes #1887 
Even I finished the tests, I am still a little confused about the difference between them as I mentioned in issue #1887.

Add tests for hasNoPath methods in abstractUrlAssert and abstractUriAssert 

---

CONTRIBUTING.md
README.md
src/main/java/org/assertj/core/presentation/Representation.java
src/test/resources/diffs/5A.txt
src/test/resources/diffs/5B.txt

* Fixes N/A
Seems there was a branch renaming, but some things didn't get renamed, causing broken links and being generally misleading. Not sure if this needs a related issue; nothing in the contrib guide so I just made the PR.

fix references to main branch

---

src/main/java/org/assertj/core/api/SoftAssertionError.java
src/main/java/org/assertj/core/error/AssertionErrorMessagesAggregator.java
src/main/java/org/assertj/core/error/AssertionErrorMessagesAggregrator.java
src/main/java/org/assertj/core/error/MultipleAssertionsError.java

* Fix typo in `AssertionErrorMessagesAggregrator` class and `aggregrateErrorMessages()` method
* Unit tests :  NO
* Javadoc with a code example (on API only) : NO

fix typo in AssertionErrorMessagesAggregrator

---

src/main/java/org/assertj/core/api/Assumptions.java
src/test/java/org/assertj/core/api/assumptions/Assumptions_assumeThat_Atomics_Test.java
src/test/java/org/assertj/core/api/assumptions/Assumptions_assumeThat_Numbers_Test.java
src/test/java/org/assertj/core/api/assumptions/Assumptions_assumeThat_Object_Test.java
src/test/java/org/assertj/core/api/assumptions/Assumptions_assumeThat_Test.java
src/test/java/org/assertj/core/api/assumptions/Assumptions_assumeThat_involving_iterable_navigation_Test.java
src/test/java/org/assertj/core/api/assumptions/Assumptions_assumeThat_with_Stream_Test.java
src/test/java/org/assertj/core/api/assumptions/Assumptions_assumeThat_with_asInstanceOf_Test.java
src/test/java/org/assertj/core/api/assumptions/Assumptions_assumeThat_with_extracting_Test.java
src/test/java/org/assertj/core/api/assumptions/Assumptions_assumeThat_with_filteredOn_Test.java
src/test/java/org/assertj/core/api/assumptions/Assumptions_assumeThat_with_succeedsWithin_Test.java
src/test/java/org/assertj/core/api/assumptions/Assumptions_assumeThat_with_various_java_8_types_Test.java
src/test/java/org/assertj/core/api/assumptions/Assumptions_assumeThat_with_various_types_Test.java
src/test/java/org/assertj/core/api/assumptions/BDDAssumptionsTest.java
src/test/java/org/assertj/core/api/assumptions/BaseAssumptionsRunnerTest.java
src/test/java/org/assertj/core/api/bytearray/ByteArrayAssert_asHexString_Test.java
src/test/java/org/assertj/core/api/bytearray/ByteArrayAssert_asString_Test.java
src/test/java/org/assertj/core/api/bytearray/ByteArrayAssert_asString_with_charset_Test.java
src/test/java/org/assertj/core/api/recursive/comparison/RecursiveComparisonAssert_assumptions_Test.java
src/test/java/org/assertj/core/util/AssertionsUtil.java

Related to cbeust/testng#2352.
* Fixes #1961 

Change precedence of assumption classes

---

src/main/java/org/assertj/core/api/junit/jupiter/SoftAssertionsExtension.java
src/test/java/org/assertj/core/api/junit/jupiter/SoftAssertionsExtension_InjectionSanityChecking_Test.java

None of these were bugs in practice, but it is easy to keep SonarCloud happy so let's do it. That way real bugs won't be masked by the false alarms.
In particular, the alleged bug in the sanity checking test - that the test class was private - was actually intentional so that JUnit 5 *wouldn't* run it directly - it was meant to be run via its subclasses. Made it abstract instead which achieves the same thing.

SonarCloud fixes for SoftAssertionsExtension

---

src/main/java/org/assertj/core/error/ElementsShouldSatisfy.java
src/main/java/org/assertj/core/error/ZippedElementsShouldSatisfy.java
src/test/java/org/assertj/core/error/ElementsShouldSatisfy_create_Test.java
src/test/java/org/assertj/core/error/ElementsShouldZipSatisfy_create_Test.java

Previously, the error was appended after the `toString` of the element that did not satisfy the requirements. This was problematic for objects with a lengthy `toString` because it made the describe error difficult to identify. Now, the describe error is on a new line allowing for quick identification.
* Fixes #2010
I think I updated all the areas needed for this change, otherwise let me know!

Improve describe error readability of ElementsShouldSatisfy

---

pom.xml

Now that Bnd 5.2.0 is released and being used by the project, we can
clean up some pom dependencies which were necessary to avoid a bad
interaction between Bnd and the enforcer plugin.

bnd: Clean up some pom dependencies now that Bnd 5.2.0 is being used

---

src/main/java/org/assertj/core/error/ShouldNotHaveSameClass.java
src/test/java/org/assertj/core/api/abstract_/AbstractAssert_doesNotHaveSameClassAs_Test.java
src/test/java/org/assertj/core/api/abstract_/AbstractAssert_hasSameClassAs_Test.java
src/test/java/org/assertj/core/error/ShouldNotHaveSameClass_create_Test.java
src/test/java/org/assertj/core/internal/objects/Objects_assertDoesNotHaveSameClassAs_Test.java

* Fixes NA
The error message of `ShouldNotHaveSameClass` is fixed because it was double negative.
Some inconsistencies were also found for the test naming convention of same class assertions while I was working on https://github.com/assertj/assertj-core/issues/2028.

Fix error mesage of ShouldNotHaveSameClass and test naming convention of same class assertions

---

src/test/java/org/assertj/core/api/future/AbstractFutureTest.java
src/test/java/org/assertj/core/api/future/CompletableFutureAssert_failsWithin_Test.java
src/test/java/org/assertj/core/api/future/CompletableFutureAssert_succeedsWithin_Test.java
src/test/java/org/assertj/core/api/future/CompletableFutureAssert_succeedsWithin_duration_Test.java
src/test/java/org/assertj/core/api/future/FutureAssert_failsWithin_Test.java
src/test/java/org/assertj/core/api/future/FutureAssert_succeedsWithin_Test.java
src/test/java/org/assertj/core/api/future/FutureAssert_succeedsWithin_duration_Test.java

fixes #2030
Basically, this pr creates a separate [executorservice](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/ExecutorService.html) for every test case and additionally a [shutdown now](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/ExecutorService.html#shutdownNow()) is performed.
This will make our future tests more stable (especially on nodes with low number of cores).
Previously, in some cases tasks from other test cases were still running.
We might go for a junit jupiter parameterresolver based solution in the future.

Use dedicated executorservice for every testcase

---

src/main/java/org/assertj/core/api/AbstractLongArrayAssert.java
src/test/java/org/assertj/core/api/longarray/LongArrayAssert_containsAnyOf_with_Long_array_Test.java
src/test/java/org/assertj/core/api/longarray/LongArrayAssert_containsExactlyInAnyOrder_with_Long_array_Test.java
src/test/java/org/assertj/core/api/longarray/LongArrayAssert_containsExactly_with_Long_array_Test.java
src/test/java/org/assertj/core/api/longarray/LongArrayAssert_containsOnlyOnce_with_Long_array_Test.java
src/test/java/org/assertj/core/api/longarray/LongArrayAssert_containsOnly_with_Long_array_Test.java
src/test/java/org/assertj/core/api/longarray/LongArrayAssert_containsSequence_with_Long_array_Test.java
src/test/java/org/assertj/core/api/longarray/LongArrayAssert_containsSubsequence_with_Long_array_Test.java
src/test/java/org/assertj/core/api/longarray/LongArrayAssert_contains_with_Long_array_Test.java
src/test/java/org/assertj/core/api/longarray/LongArrayAssert_doesNotContain_with_Long_array_Test.java
src/test/java/org/assertj/core/api/longarray/LongArrayAssert_endsWith_with_Long_array_Test.java
src/test/java/org/assertj/core/api/longarray/LongArrayAssert_startsWith_with_Long_array_Test.java

Add overloaded methods with boxed arrays for contains assertions

---

src/main/java/org/assertj/core/api/AbstractAssert.java
src/main/java/org/assertj/core/api/Assert.java
src/main/java/org/assertj/core/error/ShouldHaveToString.java
src/main/java/org/assertj/core/error/ShouldNotHaveToString.java
src/main/java/org/assertj/core/internal/Objects.java
src/test/java/org/assertj/core/api/abstract_/AbstractAssert_doesNotHaveToString_Test.java
src/test/java/org/assertj/core/error/ShouldHaveToString_create_Test.java
src/test/java/org/assertj/core/error/ShouldNotHaveToString_create_Test.java
src/test/java/org/assertj/core/internal/objects/Objects_assertDoesNotHaveToString_Test.java
src/test/java/org/assertj/core/internal/objects/Objects_assertHasToString_Test.java

* Fixes #2028 
Minor fixes for `hasToString` doc description and `ShouldHaveToString` error as well.

Add doesNotHaveToString assertion

---

src/main/java/org/assertj/core/internal/AtomicReferenceArrayElementComparisonStrategy.java
src/main/java/org/assertj/core/internal/IterableElementComparisonStrategy.java
src/main/java/org/assertj/core/internal/ObjectArrayElementComparisonStrategy.java
src/main/java/org/assertj/core/internal/StandardComparisonStrategy.java
src/test/java/org/assertj/core/internal/StandardComparisonStrategy_areEqual_Test.java
src/test/java/org/assertj/core/internal/objects/Objects_assertEqual_Test.java
verify.bndrun

The previous behavior relied on `java.util.Objects#deepEquals`, which
performs a reference check before invoking `equals` on the first
parameter. While this it not an issue for proper implementations of
the `equals` contract, it was behaving incorrectly in case of
implementations not satisfying the reflexive property. Also, performing
the reference check outside of the `equals` implementation reduced the
overall coverage.
The tests now provide thorough regression to ensure that no shortcut is
taken, especially in case of implementations violating the contract.
* Fixes #1949

Rework `StandardComparisonStrategy#areEqual` to avoid shortcuts

---

src/main/java/org/assertj/core/api/AbstractIterableAssert.java
src/main/java/org/assertj/core/api/AbstractMapAssert.java
src/main/java/org/assertj/core/api/AtomicReferenceArrayAssert.java
src/main/java/org/assertj/core/api/ListAssert.java

Seems like I forgot the AtomicReferenceArrayAssert in https://github.com/assertj/assertj-core/commit/3d5841fa110c029fc2104fd7425e02dd1ed19384. This PR fixes the possible heap pollution in that class and fixes some other heap pollution for the `ForProxy` methods by using arrays instead of varArgs.

Fix possible heap pollution in AtomicReferenceArrayAssert

---

cdg-pitest-licence.txt
pom.xml
src/main/java/org/assertj/core/api/DefaultAssertionErrorCollector.java
src/test/java/org/assertj/core/api/abstract_/AbstractAssert_equal_hashCode_Test.java
src/test/java/org/assertj/core/internal/StandardComparisonStrategy_areEqual_Test.java

This PR adds a profile so pitest can be easily run against assertj core
```bash
mvn -Ppitest test-compile
```
The plugin has been bound to the test-compile (rather than test) as an easy way of preventing surefire from also running. As pitest runs the tests itself, additional running surefire just slows feedback.
A full analysis of the project takes around 45 minutes.
The PR also adds git integration, this allows just local changes to be analysed with
```bash
mvn -Ppitest -Dfeatures="+GIT" test-compile
```
Or for changes to be brought into scope from git history
```bash
mvn -Ppitest -Dfeatures="+GIT(from[HEAD~10])" test-compile
```
Once merged, this can be built on in a future PR to provide mutation testing feedback on all incoming PRs as described here -> …

Configure pitest

---

src/main/java/org/assertj/core/api/Descriptable.java
src/main/java/org/assertj/core/error/ShouldBeEqual.java
src/main/java/org/assertj/core/error/ShouldBeEqualIgnoringCase.java
src/test/java/org/assertj/core/api/abstract_/AbstractAssert_isInstanceOfSatisfying_Test.java
src/test/java/org/assertj/core/api/atomic/reference/AtomicReferenceAssert_hasValueSatisfying_Test.java
src/test/java/org/assertj/core/error/ShouldBeEqual_Test.java
src/test/java/org/assertj/core/error/ShouldBeEqual_newAssertionError_Test.java
src/test/java/org/assertj/core/error/ShouldBeEqual_newAssertionError_differentiating_expected_and_actual_Test.java
src/test/java/org/assertj/core/error/ShouldBeEqual_newAssertionError_without_JUnit_Test.java
src/test/java/org/assertj/core/error/ShouldBeEqual_newAssertionError_without_JUnit_and_OTA4J_Test.java
src/test/java/org/assertj/core/matcher/AssertionMatcher_matches_Test.java
src/test/java/org/assertj/core/test/ErrorMessagesForTest.java

Move the trailing space after "was" to a leading space before "but" so that IntellIJ's diff regexes can pick it up
* Fixes #2199 (ignore if not applicable)

Update ShouldBeEqual assertion message

---

src/main/java/org/assertj/core/internal/StandardComparisonStrategy.java

While working on PR #2171 I noticed that the performance degradation with the changes in that PR + this change are way lower than the changes in that PR without this change here.
Did some JFR profiling and most of the time is spend in this method here. With this PR the idea is to avoid doing `instanceof` checks if the actual is not an array. I know that `Objects#deepEquals` is similar, but I cannot explain why the performance degrades so much in the AssertJ code (perhaps because I am using `Long` for the testing and the reference is the same.
I can add a different object type in the benchmark if you want

Improve performance in StandardComparisonStrategy#areEqual

---

pom.xml
src/main/java/org/assertj/core/api/AbstractMapAssert.java
src/main/java/org/assertj/core/internal/Maps.java
src/main/java/org/assertj/core/util/Lists.java
src/main/java/org/assertj/core/util/Sets.java
src/test/java/org/assertj/core/internal/MapsBaseTest.java
src/test/java/org/assertj/core/internal/maps/Maps_assertContainsExactly_Test.java
src/test/java/org/assertj/core/internal/maps/Maps_assertContainsKey_Test.java
src/test/java/org/assertj/core/internal/maps/Maps_assertContainsOnlyKeys_Test.java
src/test/java/org/assertj/core/internal/maps/Maps_assertContainsOnly_Test.java
src/test/java/org/assertj/core/internal/maps/Maps_assertDoesNotContainKeys_Test.java
src/test/java/org/assertj/core/test/Maps.java

This affects:
- `assertContainsOnly`
- `assertContainsOnlyKeys`
* Fixes #2159

Honor map key comparison semantics with `containsOnly` assertions

---

pom.xml

* Fixes: NA
* Javadoc with a code example (on API only) :  NA
As you agreed that `jdk 11` is minimum version for build we can simplify configuration in pom file.
We don't need special profile for `jdk 9`.
Additionally we can use `release` option for build `jdk 8` version instead of `source/target`.
http://openjdk.java.net/jeps/247

Remove profile for jdk9 from pom

---

src/main/java/org/assertj/core/internal/Maps.java
src/test/java/org/assertj/core/api/map/MapAssert_containsExactlyInAnyOrderEntriesOf_Test.java
src/test/java/org/assertj/core/internal/maps/Maps_assertContainsOnly_Test.java

This appears to have broken in PR #2167 specifically with the use of
`Map.remove(Object, Object)` that does not perform deep equality
checking on the map entry value (e.g. arrays).
* Fixes https://github.com/assertj/assertj-core/issues/2264

Map entry values handle deep equality comparison again

---

.github/workflows/binary-compatibility.yml
CONTRIBUTING.md
README.md
pom.xml

This adds the configuration to execute [`japicmp`](https://github.com/siom79/japicmp) for checking the binary compatibility of `main` against the latest released version. The result is printed as part of the workflow and also published as an artifact.
The new workflow runs only for push events on `main`, but an example of the run can be found here: https://github.com/assertj/assertj-core/actions/runs/962080274

Add workflow to check binary compatibility of `main` against the latest release

---

src/main/java/org/assertj/core/api/AbstractFileAssert.java
src/test/java/org/assertj/core/api/file/FileAssert_hasFileName_Test.java

* Fixes #2236
* Javadoc with a code example (on API only) : Yes

[#2236] Add hasFileName as an alias of hasName for File assertions

---

src/main/java/org/assertj/core/api/AbstractFileAssert.java
src/test/java/org/assertj/core/api/file/FileAssert_isWritable_Test.java

* Fixes #2235 
Hello! I already finished the issue, I ran the tests and seems fine, it is everything okay? :)

Add isWritable as an alias of canWrite for File assertions

---

src/main/java/org/assertj/core/api/AbstractFileAssert.java
src/test/java/org/assertj/core/api/file/FileAssert_isReadable_Test.java

* Fixes #2234
* Javadoc with a code example (on API only) : YES 

Add isReadable as an alias of canRead for File assertions

---

.github/workflows/binary-compatibility.yml
pom.xml

This adds the configuration to execute [`japicmp`](https://github.com/siom79/japicmp) for checking the binary compatibility of a branch against `main`.
An example of the run with a binary incompatible change can be found here: https://github.com/assertj/assertj-core/actions/runs/1018693097

Add binary compatibility check of branches against `main`

---

src/main/java/org/assertj/core/api/AbstractPathAssert.java
src/main/java/org/assertj/core/error/ShouldHaveSize.java
src/main/java/org/assertj/core/internal/Paths.java
src/test/java/org/assertj/core/api/path/PathAssert_hasSize_Test.java
src/test/java/org/assertj/core/error/ShouldHaveSize_create_Test.java
src/test/java/org/assertj/core/internal/paths/Paths_assertHasSize_Test.java

* Fixes #2237  
* Javadoc with a code example (on API only) : YES 
Implemented the feature `assertThat(Path).hasSize(expectedSize)`. Verifies the size in bytes of the path file.

Issue #2237 Implement hasSize to Path assertions

---

src/main/java/org/assertj/core/api/ObjectEnumerableAssert.java

Fixed inconsistency between document and code.

Fix JavaDoc for containsExactlyInAnyOrderElementsOf

---

src/main/java/org/assertj/core/api/AbstractUriAssert.java
src/main/java/org/assertj/core/api/AbstractUrlAssert.java
src/main/java/org/assertj/core/error/uri/ShouldHaveNoHost.java
src/main/java/org/assertj/core/internal/Uris.java
src/main/java/org/assertj/core/internal/Urls.java
src/test/java/org/assertj/core/api/uri/UriAssert_hasNoHost_Test.java
src/test/java/org/assertj/core/api/url/UrlAssert_hasNoHost_Test.java
src/test/java/org/assertj/core/error/uri/ShouldHaveNoHost_create_Test.java
src/test/java/org/assertj/core/internal/urls/Uris_assertHasHost_Test.java
src/test/java/org/assertj/core/internal/urls/Uris_assertHasNoHost_Test.java
src/test/java/org/assertj/core/internal/urls/Urls_assertHasHost_Test.java
src/test/java/org/assertj/core/internal/urls/Urls_assertHasNoHost_Test.java

Both java.net.URI and java.net.URL have the ability to have null
hosts set (for example in URIs that point to file-system objects,
or custom URI schemes that may be non-standard).
To match the rest of this API where methods exist to provide checks
for no fragments, queries, parameters, etc being set, this provides
host visibility checking.

Added hasNoHost to AbstractUriAssert and AbstractUrlAssert

---

src/main/java/org/assertj/core/api/Assertions.java
src/main/java/org/assertj/core/api/BDDAssertions.java
src/main/java/org/assertj/core/api/WithAssertions.java
src/test/java/org/assertj/core/api/Assertions_catchException_Test.java
src/test/java/org/assertj/core/api/Assertions_catchIOException_Test.java
src/test/java/org/assertj/core/api/Assertions_catchIllegalArgumentException_Test.java
src/test/java/org/assertj/core/api/Assertions_catchIllegalStateException_Test.java
src/test/java/org/assertj/core/api/Assertions_catchIndexOutOfBoundsException_Test.java
src/test/java/org/assertj/core/api/Assertions_catchNullPointerException_Test.java
src/test/java/org/assertj/core/api/Assertions_catchReflectiveOperationException_Test.java
src/test/java/org/assertj/core/api/Assertions_catchRuntimeException_Test.java
src/test/java/org/assertj/core/api/EntryPointAssertions_catchException_Test.java
src/test/java/org/assertj/core/api/EntryPointAssertions_catchIOException_Test.java
src/test/java/org/assertj/core/api/EntryPointAssertions_catchIllegalArgumentException_Test.java
src/test/java/org/assertj/core/api/EntryPointAssertions_catchIllegalStateException_Test.java
src/test/java/org/assertj/core/api/EntryPointAssertions_catchIndexOutOfBoundsException_Test.java
src/test/java/org/assertj/core/api/EntryPointAssertions_catchNullPointerException_Test.java
src/test/java/org/assertj/core/api/EntryPointAssertions_catchReflectiveOperationException_Test.java
src/test/java/org/assertj/core/api/EntryPointAssertions_catchRuntimeException_Test.java

issue-2397 catchThrowableOfType enriched alternatives

---

src/main/java/org/assertj/core/api/Fail.java

* Fixes: no issue
* Unit tests : No
The Fail class is final, but the constructor is protected. This seems like a little bad smell. Because `Fail` is pure static class, I changed the visibility to private.

refactor: change visibility of constructor in final util class to private

---

src/main/java/org/assertj/core/api/ClassBasedNavigableIterableAssert.java
src/main/java/org/assertj/core/presentation/StandardRepresentation.java
src/test/java/org/assertj/core/test/jdk11/ImmutableCollections.java

In few cases the simple `for` loop can be replaced with a enhanced `for` loop to improve readability and make the code cleaner.

Replaced `for` loop with enhanced `for` loop.

---

src/main/java/org/assertj/core/data/MapEntry.java
src/test/java/org/assertj/core/data/MapEntry_Test.java

The javadoc for Map.Entry.hashCode() specifies how to compute the
hashcode value for a Map Entry. This fix conforms to that
specification.

Fix MapEntry.hashCode() to conform to Map.Entry.hashCode() javadoc

---

pom.xml

This url is placed in the jar manifest as the Bundle-DocURL.
By default the project URL is `${project.parent.url}${project.artifactId}` but the actual website requires the `#`.

Fix pom url to match the actual url to the doc

---

src/test/java/org/assertj/core/api/double_/DoubleAssert_isCloseToPercentage_double_primitive_Test.java
src/test/java/org/assertj/core/api/double_/DoubleAssert_isNotCloseToPercentage_double_primitive_Test.java
src/test/java/org/assertj/core/api/double_/DoubleAssert_isNotCloseTo_double_primitive_Test.java
src/test/java/org/assertj/core/api/double_/DoubleAssert_isNotEqualTo_double_primitive_Test.java
src/test/java/org/assertj/core/api/float_/FloatAssert_isCloseToPercentage_float_primitive_Test.java
src/test/java/org/assertj/core/api/float_/FloatAssert_isNotCloseToPercentage_float_primitive_Test.java
src/test/java/org/assertj/core/api/float_/FloatAssert_isNotCloseTo_float_primitive_Test.java
src/test/java/org/assertj/core/api/float_/FloatAssert_isNotEqualTo_float_primitive_Test.java
src/test/java/org/assertj/core/api/short_/ShortAssert_isCloseToPercentage_short_primitive_Test.java
src/test/java/org/assertj/core/api/short_/ShortAssert_isCloseTo_short_primitive_Test.java
src/test/java/org/assertj/core/api/short_/ShortAssert_isNotCloseToPercentage_short_primitive_Test.java
src/test/java/org/assertj/core/api/short_/ShortAssert_isNotCloseTo_short_primitive_Test.java

Fixes the issue of MacOS not accepting files with the same name but different casing.
* Fixes: NA
* PR meets the [contributing guidelines](https://github.com/assertj/assertj-core/blob/main/CONTRIBUTING.md): NA

Fix file names to prevent MacOS casing issues

---

src/main/java/org/assertj/core/api/AbstractLocalTimeAssert.java
src/test/java/org/assertj/core/api/localtime/LocalTimeAssert_hasSecond_Test.java

* Fixes partially #2541
* Javadoc with a code example (on API only) : YES 

Add `hasSecond` to `LocalTime` assertions

---

src/main/java/org/assertj/core/api/AbstractLocalDateAssert.java

* See #2566 the last comment
* Unit tests :  NA

Fix javadoc error of `hasMonthValue` in `LocalDate` assertions

---

src/main/java/org/assertj/core/api/Assertions.java
src/main/java/org/assertj/core/api/AssertionsForClassTypes.java
src/main/java/org/assertj/core/api/BDDAssertions.java
src/main/java/org/assertj/core/api/WithAssertions.java
src/main/java/org/assertj/core/util/Files.java
src/main/java/org/assertj/core/util/Paths.java
src/test/java/org/assertj/core/api/Assertions_linesOf_Test.java
src/test/java/org/assertj/core/api/EntryPointAssertions_linesOf_Test.java
src/test/java/org/assertj/core/util/Paths_linesOf_Test.java

* Fixes #2617 
`BDDAssertions` uses `@since` in the javadoc, but wasn't sure which version to add

Add `linesOf` variants for a `Path` content

---

src/main/java/org/assertj/core/api/AbstractAssert.java
src/test/java/org/assertj/core/api/AbstractAssert_areEqual_Test.java

Prerequisite for fixing [assertj/assertj-guava#70](https://github.com/assertj/assertj-guava/issues/70#issuecomment-1057532277).
Related to #2631, supersedes #2632.

Expose `ComparisonStrategy::areEqual` in `AbstractAssert`

---

src/main/java/org/assertj/core/api/AbstractMapAssert.java
src/main/java/org/assertj/core/api/AbstractObjectArrayAssert.java
src/main/java/org/assertj/core/api/AbstractOptionalAssert.java
src/main/java/org/assertj/core/api/AtomicReferenceArrayAssert.java
src/main/java/org/assertj/core/api/InstanceOfAssertFactories.java
src/main/java/org/assertj/core/api/Java6BDDAssertions.java
src/main/java/org/assertj/core/api/ListAssert.java
src/main/java/org/assertj/core/api/ObjectEnumerableAssert.java
src/main/java/org/assertj/core/api/WithAssertions.java
src/main/java/org/assertj/core/api/junit/jupiter/SoftAssertionsExtension.java
src/test/java/org/assertj/core/internal/floats/Floats_assertLessThanOrEqualTo_Test.java
src/test/java/org/assertj/core/test/jdk11/ImmutableCollections.java

- Work around/suppress around 95 warnings produced on JDK-17 with -Xlint:all flag enabled.
- Fix a couple of warnings dotted around in tests to do with unchecked operations
- Fix incorrect javadoc reference in Floats_AssertLessThanOrEqualTo_test
Some suppressions are being marked as being redundant by IntelliJ when they are not. For these, I have added an IntelliJ-specific suppression about redundant suppressions to prevent a risk of the original suppression being accidentally removed in the future due to the false positive.
Xlint:all was run by adding 
```xml
<compilerArgs>
<arg>-Xlint:all</arg>
</compilerArgs>
```
...to the `<configuration />` block for maven-compiler-plugin in the POM.

Work around/suppress around 95 warnings produced on JDK-17 with -Xlint:all

---

src/test/java/org/assertj/core/api/future/AbstractFutureTest.java
src/test/java/org/assertj/core/api/future/FutureAssert_succeedsWithin_duration_Test.java

Addresses an issue where FutureAssert tests in CI would sometimes fail on the Windows runner due to kernel thread sleep calls.
I have increased the timeout for that call, and also implemented a custom ThreadFactory for the abstract base class which will ensure that:
1. the threads in the executor are daemon threads
2. the threads in the executor are named appropriately to assist in debugging in the future (e.g. through Java Mission Control, JMX, JConsole, or similar)
3. all uncaught exceptions get reported to the logs
4. the threads emulate PrivilegedThreadFactory in that they hold a reference to the parent thread context class loader (no need to run this in an access control block for tests).
5. the threads run with the highest priority where possible.

Fix spurious Future tests failure on Windows runners

---

.github/workflows/binary-compatibility.yml

Binary-compatibility is currently failing when attempting to add a label to 
the resource behind this integration when the person running the CI does not have
permission to manipulate that resource.
This allows that error to be ignored.

[CI fix] Allow add-label to fail in binary-compatibility.yml

---

src/main/java/org/assertj/core/internal/Strings.java

Fix typo in docs for assertIsEqualToNormalizingNewlines

---

pom.xml
src/main/java/org/assertj/core/api/AssumptionExceptionFactory.java
src/main/java/org/assertj/core/configuration/Configuration.java
src/test/java/org/assertj/core/api/EntryPointAssertions_useDefaultRepresentation_Test.java
src/test/java/org/assertj/core/api/EntryPoint_Assumptions_setPreferredAssumptionException_Test.java
src/test/java/org/assertj/core/configuration/Configuration_apply_Test.java
src/test/java/org/assertj/core/configuration/Configuration_describe_Test.java
src/test/java/org/assertj/core/extension/SoftlyExtensionInstanceTest.java
src/test/java/org/assertj/core/osgi/AssumptionsTest.java
src/test/java/org/assertj/core/presentation/StandardRepresentation_throwable_format_Test.java
src/test/java/org/assertj/core/test/MutatesGlobalConfiguration.java

Noticed when I run the tests in my IDE, sometimes there are cases where loads of tests are failing.
Seems to be related to the global state being changed, so I have added an annotation that can be placed on any test cases that manipulate the global state. This annotation will ensure the test runs in global isolation to prevent race conditions, and it will enforce resetting the global state after each test and at the end of the test execution for the class (to handle cases such as `@AfterAll` which run outside the scope of regular test cases).
I have also made Surefire now execute tests in complete random order, which should assist in identifying any other places this kind of thing is happening in

Reset global state more aggressively in tests

---

src/main/java/org/assertj/core/api/WithThrowable.java
src/test/java/org/assertj/core/api/future/CompletableFutureAssert_failsWithin_Test.java
src/test/java/org/assertj/core/api/future/FutureAssert_failsWithin_Test.java

For `AbstractFutureAssertfailsWithin(...)` and `AbstractCompletableFutureAssertfailsWithin(...)`, add a method `withThrowableThat()` to the result.
Also adjust the test cases to use this new method, in the same manner as `withThrowableOfType(...)` is tested.
Fixes #2701.

Issue 2701: add withThrowableThat

---

assertj-core/src/main/java/org/assertj/core/api/AbstractObjectAssert.java
assertj-core/src/test/java/org/assertj/core/api/object/ObjectAssert_doesNotReturn_Test.java
assertj-core/src/test/java/org/assertj/core/api/object/ObjectAssert_extracting_with_Function_Test.java
assertj-core/src/test/java/org/assertj/core/api/object/ObjectAssert_returns_Test.java

Honor custom type comparators with `returns` and `doesNotReturn`

---

assertj-core/src/main/java/org/assertj/core/internal/Dates.java

A local variable is declared and in the next line returned. This can be replaced by an instant return.
* Inlined return statement return checkLowerBoundaryPeriod && checkUpperBoundaryPeriod
* Fixes Code Style Issue reported by IntelliJ
* Unit tests :  NA
* Javadoc with a code example (on API only) : YES / NO / NA

style: Repair code style issues in org.assertj.core.internal.Dates

---

assertj-tests/assertj-integration-tests/assertj-core-kotlin/pom.xml
assertj-tests/assertj-integration-tests/assertj-core-kotlin/src/test/kotlin/org/assertj/core/tests/kotlin/Assertions_assertThat_Test.kt
assertj-tests/assertj-integration-tests/pom.xml

fixes #2757 
I've added a very first kotlin test (for sure we have to extend/fine tune it laster on).
see
```
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ assertj-core-kotlin ---
[INFO] Surefire report directory: /home/runner/work/assertj/assertj/assertj-tests/assertj-integration-tests/assertj-core-kotlin/target/surefire-reports
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.assertj.core.tests.kotlin.Assertions_assertThat_Test
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.12 s - in org.assertj.core.tests.kotlin.Assertions_assertThat_Test
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0 …
```

Add integration test infrastructure for Kotlin

---

assertj-core/src/main/java/org/assertj/core/api/ObjectAssert.java

Deprecate `ObjectAssert(AtomicReference)`

---

.github/workflows/binary-compatibility.yml
.github/workflows/main.yml
.github/workflows/pitest-receive-pr.yml

Returns cache from `actions/setup-java`.
According to https://github.com/actions/setup-java/issues/305 should be fixed.

Return cache in `setup-java` action

---

assertj-tests/assertj-integration-tests/pom.xml

The underlying ASM has been upgraded to version 9.4 in #2815 which supports Java 20 bytecode.

Allow Java 20 with Groovy tests

---

assertj-core/src/main/java/org/assertj/core/api/ClassBasedNavigableIterableAssert.java
assertj-core/src/main/java/org/assertj/core/api/ClassBasedNavigableListAssert.java

The issue with `java.lang.reflect.Constructor#getParameterTypes()` is that each time it creates a new array by `clone` method.
It does not make sense to do it in order to only get number of parameter types

Use getParameterCount rather than getParameterTypes().length

---

assertj-guava/pom.xml
assertj-guava/verify.bndrun
assertj-tests/assertj-integration-tests/assertj-core-osgi/pom.xml
assertj-tests/assertj-integration-tests/assertj-core-osgi/verify.bndrun

Bnd 6.4.0 allows writing and reading bndrun files from different folders. So we change to use this feature so that the resolver plugin writes the resolved bndrun file to the target folder and the testing plugin uses the resolved bndrun file from the target folder.
This change means that running the maven build does not modify checked in source (bndrun files).

build: Use Bnd feature to write resolved bndrun files to output folder

---

assertj-core/src/main/java/org/assertj/core/api/AbstractClassAssert.java
assertj-core/src/main/java/org/assertj/core/error/ShouldBeRecord.java
assertj-core/src/test/java/org/assertj/core/api/classes/ClassAssert_isNotRecord_Test.java
assertj-core/src/test/java/org/assertj/core/api/classes/ClassAssert_isRecord_Test.java
assertj-tests/assertj-integration-tests/assertj-core-groovy/src/test/groovy/org/assertj/core/tests/groovy/StandardRepresentation_using_GString_Test.groovy
assertj-tests/assertj-integration-tests/assertj-core-java-17/pom.xml
assertj-tests/assertj-integration-tests/assertj-core-java-17/src/test/java/org/assertj/core/tests/java17/Assertions_assertThat_with_Record_Test.java
assertj-tests/assertj-integration-tests/assertj-core-java-17/src/test/java/org/assertj/core/tests/java17/RecordTest.java
assertj-tests/assertj-integration-tests/pom.xml

* Fixes NA
Add `isRecord()` and `isNotRecord()` Class assertions.
As `record` only landed in Java 16 I'm having to use reflection to check whether the class is a record or not. I'm also only able to add unit tests for the negative cases, because I can't compile code that uses `record`.
If this is accepted I thought I'd also open a PR that adds a `hasRecordComponents` assertion.

Add isRecord() and isNotRecord() Class assertions

---

assertj-core/src/main/java/org/assertj/core/api/recursive/comparison/ComparisonDifference.java

Check List:
Fixes absense of getters for field path in ComparisonDifference
Unit tests : NA
Javadoc with a code example (on API only) : NA
PR meets the [contributing guidelines](https://github.com/assertj/assertj/blob/main/CONTRIBUTING.md)
org.assertj.core.api.recursive.comparison.ComparisonDifference unnecessery closes access to both decomposedPath and concatenatedPath.
org.assertj.core.api.recursive.comparison.RecursiveComparisonDifferenceCalculator#determineDifferences is a public method but you cannot get a field path from its result. It would be nice to have getters on it to use in an application code.

Add getters for field path in ComparisonDifference

---

assertj-core/src/main/java/org/assertj/core/presentation/StandardRepresentation.java
assertj-core/src/test/java/org/assertj/core/api/iterable/IterableAssert_doNotBreakOnFailingTestsForDirectoryStreams.java
assertj-core/src/test/java/org/assertj/core/presentation/StandardRepresentation_iterable_format_Test.java

The DirectoryStream class is somewhat special because the API allows it to only support .iterator() being called at most once on any implementations. Due to the nature of how the StandardRepresentation currently works for iterable types, any assertion error that is thrown as a result of assertions failing on a DirectoryStream object can result in IllegalStateExceptions being propagated to the caller if .iterator() has already been called on the class. This can break further if using soft assertions, as the state of the class could change unexpectedly resulting in different exceptions being raised depending on the execution order.
I've added a mechanism to deal with allowing the definition of so-called 'blacklisted' iterable types, just in case other cases like this appear in the JRE …

Fixes a bug when failing assertions on DirectoryStream types

---

.mvn/maven.config
.mvn/wrapper/MavenWrapperDownloader.java
.mvn/wrapper/maven-wrapper.properties
mvnw
mvnw.cmd

- use secure license url
- make sure releases include sha512 and sha256 checksums in addition to defaults
- make sure build considers downloading stronger checksums
- bump to maven 3.9.2
note: 
* running wrapper to update will not produce secure license url at this time.
* by default, maven now uses header data to determine what checksum to download.  Until all package managers catch up, that means it will fall back to sha1 or md5.  The smart checksums false allows it to check for secure checksums.
* The checksum algorithms will be deployed in additionl to the defaults sha1 and md5 with this change.

[mvn] Update maven wrapper

---

assertj-core/src/main/java/org/assertj/core/internal/Iterables.java
assertj-core/src/test/java/org/assertj/core/internal/iterables/Iterables_assertAnyMatch_Test.java

This PR fixes a null pointer exception produced by the following usage:
```java
assertThat(Arrays.asList("foo", null)).anyMatch(Objects::isNull);
```
I came across the exception while trying to assert that a collection contains both, null and non-null values:
```java
assertThat(Arrays.asList("foo", null))
.anyMatch(Objects::isNull)
.anyMatch(Objects::nonNull);
```
The alternative is to use `containsNull()`:
```java
assertThat(Arrays.asList("foo", null)
.containsNull()
.anyMatch(Objects::nonNull);
```
Following the [contributing …

Fix NPE thrown by `anyMatch(Objects::isNull)` given an iterable containing a null element

---

assertj-core/src/main/java/org/assertj/core/api/AbstractAssert.java
assertj-core/src/main/java/org/assertj/core/api/Assert.java
assertj-core/src/main/java/org/assertj/core/api/SoftProxies.java
assertj-core/src/test/java/org/assertj/core/api/Assertions_assertThat_asList_Test.java
assertj-core/src/test/java/org/assertj/core/api/BDDSoftAssertionsTest.java
assertj-core/src/test/java/org/assertj/core/api/SoftAssertionsTest.java
assertj-core/src/test/java/org/assertj/core/api/assumptions/Assumptions_assumeThat_Object_Test.java
assertj-core/src/test/java/org/assertj/core/internal/IterableDiff_Test.java

Triggered by https://github.com/assertj/assertj/issues/3105#issuecomment-1633150460.

Deprecate `asList` in favor of `asInstanceOf`

---

assertj-core/pom.xml

It's defined in the parent POM already via https://github.com/assertj/assertj/blob/55356a5254e9a50881301bbfaaa32f1a23d1dc2d/assertj-parent/pom.xml#L236-L238

Remove duplicate maven version

---

assertj-parent/pom.xml

This makes it possible to invoke maven without arguments in the root module.
* Fixes #3181

Remove default goal

---

.github/workflows/cross-version.yml
.github/workflows/main.yml

Currently, most of the jobs are failing due to maxcellent/javadoc.io#180.
This change isolates the Javadoc generation into a separate job so that the unavailability of [javadoc.io](https://javadoc.io) doesn't cause other jobs to fail.

Move Javadoc generation to separate job

---

assertj-core/src/main/java/org/assertj/core/api/recursive/comparison/RecursiveComparator.java
assertj-core/src/test/java/org/assertj/core/api/recursive/comparison/RecursiveComparator_constructor_Test.java

This allows a simpler creation of a `RecursiveComparator` instance for cases where a custom `RecursiveComparisonConfiguration` is not required.
Originally inspired by https://stackoverflow.com/questions/77151593.

Add default constructor for `RecursiveComparator`

---

assertj-core/src/main/java/org/assertj/core/api/AbstractOffsetDateTimeAssert.java

`AbstractOffsetDateTimeAssert#isBetween` should use `inclusive`, not `exclusive`
Also checked other Date/Time asserts and tests: seems like in other classes the parameter names are valid.
* Fixes: chore argument renaming
* Javadoc with a code example (on API only) : NA (autogenerated)

Update misleading parameter name AbstractOffsetDateTimeAssert#isBetween

---

assertj-core/src/main/java/org/assertj/core/api/AbstractObjectAssert.java
assertj-core/src/test/java/org/assertj/core/api/object/ObjectAssert_doesNotReturn_Test.java
assertj-core/src/test/java/org/assertj/core/api/object/ObjectAssert_returns_Test.java

Invoke `isNotNull` in `returns` and `doesNotReturn`

---

assertj-core/src/main/java/org/assertj/core/api/Assertions.java
assertj-core/src/main/java/org/assertj/core/api/BDDAssertions.java
assertj-core/src/main/java/org/assertj/core/api/ThrowableAssert.java
assertj-core/src/test/java/org/assertj/core/api/Assertions_assertThatThrownBy_Test.java
assertj-core/src/test/java/org/assertj/core/api/throwable/ThrowableAssert_built_from_ThrowingCallable_Test.java
assertj-core/src/test/java/org/assertj/core/api/throwable/ThrowableAssert_built_with_then_method_Test.java

This reverts commit cf06398587da23ac530b03a941e0efe6cf29aef7, related to #3043.
Fixes #3314.

Revert "Provide value when assertThatThrownBy/thenThrownBy fail"

---

assertj-core/src/main/java/org/assertj/core/internal/Maps.java
assertj-core/src/test/java/org/assertj/core/internal/MapsBaseTest.java
assertj-core/src/test/java/org/assertj/core/internal/maps/Maps_assertContainsExactly_Test.java
assertj-core/src/test/java/org/assertj/core/internal/maps/Maps_assertContainsKeys_Test.java

This reverts commit 498ee5bb0a5cc367420cdb3c8e0e93d6e4bf5e51 and adds new tests to prevent further regressions.
Fixes #3315, fixes #3317, reopens #2165.

Revert "fix: containsExactly does not work properly with maps not using equals to compare keys"

---

assertj-core/src/main/java/org/assertj/core/api/AbstractAssert.java

doc: deprecation notice visible in AbstractAssert#asList

---

assertj-guava/src/main/java/org/assertj/guava/api/MultimapAssert.java
assertj-guava/src/test/java/org/assertj/guava/api/MultimapAssert_doesNotContainKeys_Test.java

Behavior matches the asserts for regular java.util Map asserts in core.

Add `doesNotContainKey` and `doesNotContainKeys` to Guava `Multimap` assertions

---

assertj-core/pom.xml
assertj-core/src/main/java/org/assertj/core/api/AbstractAssert.java
assertj-core/src/main/java/org/assertj/core/api/AssertFactory.java
assertj-core/src/main/java/org/assertj/core/api/InstanceOfAssertFactories.java
assertj-core/src/main/java/org/assertj/core/api/InstanceOfAssertFactory.java
assertj-core/src/test/java/org/assertj/core/api/InstanceOfAssertFactoriesTest.java
assertj-core/src/test/java/org/assertj/core/api/InstanceOfAssertFactoryTest.java

Add `createAssert(ValueProvider)` to `AssertFactory`

---

assertj-core/src/main/java/org/assertj/core/api/AbstractIteratorAssert.java
assertj-core/src/test/java/org/assertj/core/api/iterator/IteratorAssert_isUnmodifiable_Test.java

* Fixes: #3458 
* Unit tests: YES
* Javadoc with a code example (on API only): YES
I can only check if an iterator is unmodifiable by calling `remove()` and checking if the iterator throws `UnsupportedOperationException`. However not all unmodifiable iterators behave like that, see [my comment](https://github.com/assertj/assertj/issues/3458#issuecomment-2111116003) in the ticket. 
That's why I check explicitly for `Collections$EmptyIterator`  and `Collections$EmptyListIterator`.
cc @scordio

#3458 isUnmodifiable assertion for Iterator instances

---

assertj-core/src/main/java/org/assertj/core/api/AbstractCharArrayAssert.java
assertj-core/src/main/java/org/assertj/core/api/AbstractCharSequenceAssert.java
assertj-core/src/main/java/org/assertj/core/api/AbstractCharacterAssert.java
assertj-core/src/main/java/org/assertj/core/api/Char2DArrayAssert.java

They are already processed by the Java compiler, so previously instead of the Unicode escape the corresponding character was shown.
See for example [`AbstractCharacterAssert#inUnicode()` Javadoc](https://javadoc.io/doc/org.assertj/assertj-core/latest/org/assertj/core/api/AbstractCharacterAssert.html#inUnicode()):
Notice how it does not show the Unicode escape.
I chose the HTML character reference `&bsol;` as replacement for `\`, but other approaches might work as well.
Following the [contributing guidelines](https://github.com/assertj/assertj/blob/main/CONTRIBUTING.md) will make it …

Fix Unicode escapes in `inUnicode()` Javadoc

---

assertj-core/src/main/java/org/assertj/core/api/AbstractObjectAssert.java
assertj-tests/assertj-integration-tests/assertj-core-tests/src/test/java/org/assertj/tests/core/api/object/ObjectAssert_extracting_with_Function_Array_Test.java

before it was always Object. This resolves #3372.
```
Co-authored-by: IvoHD <IvoHD@users.noreply.github.com>
Co-authored-by: Alexandra Junghans <alexandra-junghans@users.noreply.github.com>
Co-authored-by: Mahmoud Ben Hassine <fmbenhassine@users.noreply.github.com>
```

Propagate common basetype for the `extracting` method

---

assertj-core/src/main/java/org/assertj/core/error/ShouldNotContainCharSequence.java
assertj-core/src/test/java/org/assertj/core/error/ShouldNotContainThrowable_create_Test.java

Apologies, double checking, I don't think the previous [PR ](https://github.com/assertj/assertj/pull/3686) was implemented correctly. 😓 Using [ShouldContainThrowable_create_Test](https://github.com/shaikhu/assertj/blob/3.x/assertj-core/src/test/java/org/assertj/core/error/ShouldContainThrowable_create_Test.java) as a basis, this PR has the correct implementation.
* Fixes #1355

Add throwable stacktrace to ShouldNotContainCharSequence - Correct message

---

assertj-core/src/main/java/org/assertj/core/internal/AbstractComparisonStrategy.java

Simplity is less than or eq to

---

assertj-guava/src/main/java/org/assertj/guava/api/TableAssert.java
assertj-tests/assertj-integration-tests/assertj-guava-tests/src/test/java/org/assertj/tests/guava/api/TableAssert_isEmpty_Test.java
assertj-tests/assertj-integration-tests/assertj-guava-tests/src/test/java/org/assertj/tests/guava/api/TableAssert_isNotEmpty_Test.java

The `TableAssert` currently contains `isEmpty()` assertion, but no `isNotEmpty()`. I want to extend this to be like other collection assertions.
* A new assertion `isNotEmpty()` added to the `TableAssert` class
* Added unit tests for `TableAssert#isNotEmpty()`
* Fixed typo in the `TableAssert_isEmpty_Test#should_fail_if_actual_is_null()` test method

Add `isNotEmpty` to `Table` assertions

---

pom.xml

That's the recommended way to work with licenses in the Maven POM, see https://maven.apache.org/pom.html#Licenses

Declare license using SPDX identifier

---

assertj-core/src/main/java/org/assertj/core/api/recursive/comparison/RecursiveComparisonDifferenceCalculator.java
assertj-tests/assertj-integration-tests/assertj-core-tests/src/test/java/org/assertj/tests/core/api/recursive/comparison/RecursiveComparisonAssert_isEqualTo_ignoringFields_Test.java

Restore support for null-valued maps when ignoring fields

---

assertj-core/src/main/java/org/assertj/core/api/AbstractObjectAssert.java
assertj-tests/assertj-integration-tests/assertj-core-kotlin/src/test/kotlin/org/assertj/tests/core/kotlin/api/object_/ObjectAssert_extracting_with_Function_Test.kt
assertj-tests/assertj-integration-tests/assertj-core-tests/src/test/java/org/assertj/tests/core/api/object/ObjectAssert_extracting_with_Function_Array_Test.java

Revert "Propagate common basetype for the `extracting` method (#3673)"

---

assertj-core/src/test/java/org/assertj/core/internal/PathsBaseTest.java
assertj-core/src/test/java/org/assertj/core/internal/paths/Paths_assertEndsWithRaw_Test.java
assertj-core/src/test/java/org/assertj/core/internal/paths/Paths_assertEndsWith_Test.java
assertj-core/src/test/java/org/assertj/core/internal/paths/Paths_assertExistsNoFollowLinks_Test.java
assertj-core/src/test/java/org/assertj/core/internal/paths/Paths_assertExists_Test.java
assertj-core/src/test/java/org/assertj/core/internal/paths/Paths_assertHasFileName_Test.java
assertj-core/src/test/java/org/assertj/core/internal/paths/Paths_assertHasNoParentRaw_Test.java
assertj-core/src/test/java/org/assertj/core/internal/paths/Paths_assertHasNoParent_Test.java
assertj-core/src/test/java/org/assertj/core/internal/paths/Paths_assertHasParentRaw_Test.java
assertj-core/src/test/java/org/assertj/core/internal/paths/Paths_assertHasParent_Test.java
assertj-core/src/test/java/org/assertj/core/internal/paths/Paths_assertIsCanonical_Test.java
assertj-core/src/test/java/org/assertj/core/internal/paths/Paths_assertIsSymbolicLink_Test.java
assertj-core/src/test/java/org/assertj/core/internal/paths/Paths_assertNotExists_Test.java
assertj-core/src/test/java/org/assertj/core/internal/paths/Paths_assertStartsWithRaw_Test.java
assertj-core/src/test/java/org/assertj/core/internal/paths/Paths_assertStartsWith_Test.java

Abort tests when symbolic links cannot be created

---

assertj-core/src/main/java/org/assertj/core/api/InstanceOfAssertFactories.java
assertj-core/src/test/java/org/assertj/core/api/InstanceOfAssertFactoriesTest.java

Expect component type for `array` and `array2D` factories

---

assertj-core/pom.xml
assertj-guava/pom.xml
assertj-parent/pom.xml

This change bumps:
* `byte-buddy.version` from 1.15.11 to 1.17.7
* `guava.version` from 33.4.0-jre to 33.4.8-jre
* `junit-jupiter.version` from 5.11.4 to 5.13.4
Closes #3946.

Update production dependencies
