- src/main/java/org/assertj/core/api/ComparableAssert.java
- src/main/java/org/assertj/core/api/NumberAssert.java
> Javadoc improvements and corrections

- src/test/java/org/assertj/core/api/Tuple_Test.java
- src/test/java/org/assertj/core/api/WritableAssertionInfo_toString_Test.java
- src/test/java/org/assertj/core/api/iterable/IterableAssert_usingFieldByFieldElementComparator_Test.java
- src/test/java/org/assertj/core/api/objectarray/ObjectArrayAssert_usingFieldByFieldElementComparator_Test.java
- src/test/java/org/assertj/core/condition/AllOf_toString_Test.java
- src/test/java/org/assertj/core/condition/AnyOf_toString_Test.java
- src/test/java/org/assertj/core/condition/DoesNotHave_toString_Test.java
- src/test/java/org/assertj/core/condition/Not_toString_Test.java
- src/test/java/org/assertj/core/data/Index_toString_Test.java
- src/test/java/org/assertj/core/data/MapEntry_toString_Test.java
- src/test/java/org/assertj/core/data/Offset_toString_Test.java
- src/test/java/org/assertj/core/description/Description_toString_Test.java
- src/test/java/org/assertj/core/description/TextDescription_toString_Test.java
- src/test/java/org/assertj/core/error/BasicErrorMessageFactory_toString_Test.java
- src/test/java/org/assertj/core/error/BasicErrorMessageFactory_unquotedString_Test.java
- src/test/java/org/assertj/core/error/ConstructorInvoker_newInstance_Test.java
- src/test/java/org/assertj/core/internal/ComparatorBasedComparisonStrategy_toString_Test.java
- src/test/java/org/assertj/core/internal/IgnoringFieldsComparator_toString_Test.java
- src/test/java/org/assertj/core/internal/OnFieldsComparator_toString_Test.java
hasToString() instead of "toString().isEqualTo()"
isInstanceOf() instead of "instanceof isTrue()"
> use more specific assertions for some tests

- src/main/java/org/assertj/core/api/AbstractObjectAssert.java
- src/main/java/org/assertj/core/api/AbstractUriAssert.java
- src/main/java/org/assertj/core/api/AssertFactory.java
- src/main/java/org/assertj/core/api/Assertions.java
- src/main/java/org/assertj/core/api/ClassBasedNavigableIterableAssert.java
- src/main/java/org/assertj/core/api/ClassBasedNavigableListAssert.java
- src/main/java/org/assertj/core/api/FactoryBasedNavigableIterableAssert.java
- src/main/java/org/assertj/core/api/FactoryBasedNavigableListAssert.java
- src/main/java/org/assertj/core/api/Java6AbstractBDDSoftAssertions.java
- src/main/java/org/assertj/core/api/Java6AbstractStandardSoftAssertions.java
- src/main/java/org/assertj/core/api/Java6BDDAssertions.java
- src/main/java/org/assertj/core/api/Java6BDDSoftAssertions.java
- src/main/java/org/assertj/core/api/Java6JUnitBDDSoftAssertions.java
- src/main/java/org/assertj/core/api/Java6JUnitSoftAssertions.java
- src/main/java/org/assertj/core/api/Java6SoftAssertions.java
- src/main/java/org/assertj/core/api/ObjectAssertFactory.java
> add missing since javadoc tags for version 2.5.0

- src/main/java/org/assertj/core/api/AbstractBDDSoftAssertions.java
- src/main/java/org/assertj/core/api/AbstractStandardSoftAssertions.java
- src/main/java/org/assertj/core/api/Assertions.java
- src/main/java/org/assertj/core/api/BDDAssertions.java
- src/main/java/org/assertj/core/api/Java6AbstractBDDSoftAssertions.java
- src/main/java/org/assertj/core/api/Java6AbstractStandardSoftAssertions.java
- src/main/java/org/assertj/core/api/Java6Assertions.java
- src/main/java/org/assertj/core/api/Java6BDDAssertions.java
- src/main/java/org/assertj/core/util/CheckReturnValue.java
* Fixes #157
Backports https://github.com/joel-costigliola/assertj-core/pull/695
> CheckReturnValue for assertThat statements for Findbugs

- pom.xml
> #701 - fixed issue on manifest generation removing duplicated execution

- CONTRIBUTING.md
> small improvement of CONTRIBUTING.md

- src/main/java/org/assertj/core/api/Assertions.java
- src/main/java/org/assertj/core/api/BDDAssertions.java
> minimal improvement of entry point javadoc

- src/main/java/org/assertj/core/api/Assertions.java
> remove commented out code of Assertions class

- src/main/java/org/assertj/core/api/Java6AbstractBDDSoftAssertions.java
- src/main/java/org/assertj/core/api/Java6AbstractStandardSoftAssertions.java
- src/main/java/org/assertj/core/api/Java6Assertions.java
- src/main/java/org/assertj/core/api/Java6JUnitBDDSoftAssertions.java
- src/main/java/org/assertj/core/api/Java6JUnitSoftAssertions.java
- src/main/java/org/assertj/core/api/Java6SoftAssertions.java
> make Java6*Assertions class comments similar

- src/main/scripts/convert-junit-assertions-to-assertj-on-osx.sh
- src/main/scripts/convert-junit-assertions-to-assertj.sh
- src/main/scripts/convert-testng-assertions-to-assertj.sh
> minimal stylistic improvements of the output of the conversion scripts

- pom.xml
> update dependencies to their most recent versions - master

- pom.xml
> update dependencies to their most recent versions - 2.x

- src/main/java/org/assertj/core/api/AutoCloseableBDDSoftAssertions.java
> fix AutoCloseableBDDSoftAssertions javadoc

- src/main/java/org/assertj/core/data/MapEntry.java
> add missing generic parameters to javadoc of MapEntry

- pom.xml
> remove unused easymock dependency

- pom.xml
> update junit-dataprovider version to 1.12.0

- src/main/java/org/assertj/core/api/AbstractIterableAssert.java
- src/main/java/org/assertj/core/api/AbstractMapAssert.java
> minimal javadoc improvements

- src/main/java/org/assertj/core/api/AbstractThrowableAssert.java
> several minimal improvements to the AbstractThrowableAssert javadoc

- src/main/java/org/assertj/core/api/AbstractListAssert.java
- src/main/java/org/assertj/core/api/AbstractUriAssert.java
- src/main/java/org/assertj/core/api/AbstractUrlAssert.java
- src/main/java/org/assertj/core/api/ArraySortedAssert.java
- src/main/java/org/assertj/core/internal/Lists.java
> small javadoc corrections

- src/main/java/org/assertj/core/api/AbstractIterableAssert.java
- src/main/java/org/assertj/core/api/AbstractObjectArrayAssert.java
- src/main/java/org/assertj/core/api/ObjectEnumerableAssert.java
> small javadoc improvements and corrections

- src/main/java/org/assertj/core/api/AbstractBigDecimalAssert.java
- src/main/java/org/assertj/core/api/AbstractByteAssert.java
- src/main/java/org/assertj/core/api/AbstractCharSequenceAssert.java
- src/main/java/org/assertj/core/api/AbstractDoubleAssert.java
- src/main/java/org/assertj/core/api/AbstractFloatAssert.java
- src/main/java/org/assertj/core/api/AbstractIntegerAssert.java
- src/main/java/org/assertj/core/api/AbstractLongAssert.java
- src/main/java/org/assertj/core/api/AbstractShortAssert.java
- src/main/java/org/assertj/core/api/Assertions.java
- src/main/java/org/assertj/core/api/FloatingPointNumberAssert.java
- src/main/java/org/assertj/core/api/Java6Assertions.java
- src/main/java/org/assertj/core/api/NumberAssert.java
> add missing since tags (2.x)

- src/site/site.xml
* Fixes: NA
Updates site page to latest maven xsd / fluido plugin
> [site] Update maven-fluido-skin to 1.6

- src/main/java/org/assertj/core/error/OptionalShouldContainInstanceOf.java
- src/test/java/org/assertj/core/error/OptionalShouldContainInstanceOf_create_Test.java
* Fixes #812
* Unit tests : YES (existing tests)
> Improve error message for "optional.containsInstanceOf()"

- src/test/java/org/assertj/core/api/Java6Assertions_fail_Test.java
> Fix test class name

- src/main/java/org/assertj/core/api/AbstractFutureAssert.java
- src/main/java/org/assertj/core/api/Assertions.java
- src/main/java/org/assertj/core/api/BDDAssertions.java
- src/main/java/org/assertj/core/api/FutureAssert.java
- src/main/java/org/assertj/core/api/Java6AbstractBDDSoftAssertions.java
- src/main/java/org/assertj/core/api/Java6AbstractStandardSoftAssertions.java
- src/main/java/org/assertj/core/api/Java6Assertions.java
- src/main/java/org/assertj/core/api/Java6BDDAssertions.java
- src/main/java/org/assertj/core/error/future/ShouldBeCancelled.java
- src/main/java/org/assertj/core/error/future/ShouldBeCompleted.java
- src/main/java/org/assertj/core/error/future/ShouldBeDone.java
- src/main/java/org/assertj/core/error/future/ShouldNotBeCancelled.java
- src/main/java/org/assertj/core/error/future/ShouldNotBeCompleted.java
- src/main/java/org/assertj/core/error/future/ShouldNotBeDone.java
- src/main/java/org/assertj/core/internal/Futures.java
- src/test/java/org/assertj/core/api/FutureAssertBaseTest.java
- src/test/java/org/assertj/core/api/future/FutureAssert_isCancelled_Test.java
- src/test/java/org/assertj/core/api/future/FutureAssert_isDone_Test.java
- src/test/java/org/assertj/core/api/future/FutureAssert_isNotCancelled_Test.java
- src/test/java/org/assertj/core/api/future/FutureAssert_isNotDone_Test.java
rebased #750 and added since javadoc tags
> Introduce assertions for Future

- src/test/java/org/assertj/core/api/BDDAssertionsTest.java
> fix BDDAssertionsTest case

- src/test/java/org/assertj/core/util/Arrays_nonNullElementsIn_Test.java
- src/test/java/org/assertj/core/util/Files_fileNamesIn_Test.java
- src/test/java/org/assertj/core/util/IterableUtil_nonNullElementsIn_Test.java
- src/test/java/org/assertj/core/util/Lists_newArrayList_withIterable_Test.java
- src/test/java/org/assertj/core/util/Lists_newArrayList_withVarArgs_Test.java
- src/test/java/org/assertj/core/util/Sets_newLinkedHashSet_GenericArray_Test.java
> simplify emptiness checks

- src/test/java/org/assertj/core/util/Files_fileNamesIn_Test.java
- src/test/java/org/assertj/core/util/Files_newFile_Test.java
- src/test/java/org/assertj/core/util/Files_newFolder_Test.java
- src/test/java/org/assertj/core/util/Files_newTemporaryFile_Test.java
- src/test/java/org/assertj/core/util/Files_newTemporaryFolder_Test.java
- src/test/java/org/assertj/core/util/Files_temporaryFolder_Test.java
> simplify some assertions

- src/test/java/org/assertj/core/api/Assertions_useRepresentation_Test.java
- src/test/java/org/assertj/core/api/date/DateAssert_with_string_based_date_representation_Test.java
- src/test/java/org/assertj/core/api/fail/Fail_fest_elements_stack_trace_filtering_Test.java
- src/test/java/org/assertj/core/error/ShouldBeEqual_assertj_elements_stack_trace_filtering_Test.java
- src/test/java/org/assertj/core/internal/bigdecimals/BigDecimals_assertIsNotZero_Test.java
- src/test/java/org/assertj/core/internal/bigdecimals/BigDecimals_assertIsZero_Test.java
…xpected exception was not thrown
>  make tests that expect an exception to be thrown fail if no exception was thrown

- src/test/java/org/assertj/core/api/abstract_/AbstractAssert_failWithMessage_Test.java
- src/test/java/org/assertj/core/api/iterable/IterableAssert_filteredOn_Test.java
- src/test/java/org/assertj/core/api/iterable/IterableAssert_flatExtracting_with_String_parameter_Test.java
- src/test/java/org/assertj/core/api/objectarray/ObjectArrayAssert_filteredOn_Test.java
- src/test/java/org/assertj/core/api/objectarray/ObjectArrayAssert_filteredOn_in_Test.java
- src/test/java/org/assertj/core/api/objectarray/ObjectArrayAssert_flatExtracting_with_String_parameter_Test.java
- src/test/java/org/assertj/core/api/objectarray/ObjectArrayAssert_hasSameSizeAs_with_Arrays_Test.java
- src/test/java/org/assertj/core/internal/files/Files_assertSameContentAs_Test.java
- src/test/java/org/assertj/core/test/ExpectedException.java
> More expected exception 2

- src/main/java/org/assertj/core/internal/StandardComparisonStrategy.java
> remove duplicated license header of StandardComparisonStrategy

- src/test/java/org/assertj/core/api/iterable/IterableAssert_filteredOnNull_Test.java
- src/test/java/org/assertj/core/api/iterable/IterableAssert_filteredOn_Test.java
- src/test/java/org/assertj/core/api/iterable/IterableAssert_filteredOn_condition_Test.java
- src/test/java/org/assertj/core/api/iterable/IterableAssert_filteredOn_in_Test.java
- src/test/java/org/assertj/core/api/iterable/IterableAssert_filteredOn_notIn_Test.java
- src/test/java/org/assertj/core/api/iterable/IterableAssert_filteredOn_not_Test.java
- src/test/java/org/assertj/core/api/objectarray/ObjectArrayAssert_filteredOn_Test.java
- src/test/java/org/assertj/core/api/objectarray/ObjectArrayAssert_filteredOn_condition_Test.java
- src/test/java/org/assertj/core/api/objectarray/ObjectArrayAssert_filteredOn_in_Test.java
- src/test/java/org/assertj/core/api/objectarray/ObjectArrayAssert_filteredOn_notIn_Test.java
- src/test/java/org/assertj/core/api/objectarray/ObjectArrayAssert_filteredOn_not_Test.java
> remove duplicated apache license headers

- src/test/java/org/assertj/core/internal/doubles/Doubles_assertIsNotNaN_Test.java
- src/test/java/org/assertj/core/internal/floats/Floats_assertIsNotNaN_Test.java
> fix isNotNaN failure tests

- src/test/java/org/assertj/core/util/diff/ChunkTest.java
- src/test/java/org/assertj/core/util/diff/Delta_equals_hashCode_Test.java
> add missing tests for Delta and Chunk

- src/test/java/org/assertj/core/api/FutureAssertBaseTest.java
- src/test/java/org/assertj/core/api/future/FutureAssert_isCancelled_Test.java
- src/test/java/org/assertj/core/api/future/FutureAssert_isDone_Test.java
- src/test/java/org/assertj/core/api/future/FutureAssert_isNotCancelled_Test.java
- src/test/java/org/assertj/core/api/future/FutureAssert_isNotDone_Test.java
> add missing failure test for FutureAssert

- src/main/java/org/assertj/core/api/WithAssertions.java
> add CheckReturnValue annotations to WithAssertions#assertThat

- src/test/java/org/assertj/core/api/Assertions_useRepresentation_Test.java
- src/test/java/org/assertj/core/internal/throwables/Throwables_assertHasMessageMatching_Test.java
- src/test/java/org/assertj/core/navigation/GenericNavigableAssert_Test.java
- src/test/java/org/assertj/core/util/xml/XmlStringPrettyFormatter_prettyFormat_Test.java
> convert some tests to use ExpectedException (2.x)

- src/main/java/org/assertj/core/api/Assertions.java
> add missing since javadoc tags to Assertions#assertThat*Exception

- src/main/java/org/assertj/core/api/AbstractAtomicFieldUpdaterAssert.java
- src/main/java/org/assertj/core/api/AbstractFileAssert.java
- src/main/java/org/assertj/core/api/AbstractPathAssert.java
- src/main/java/org/assertj/core/api/filter/Filters.java
- src/main/java/org/assertj/core/data/Index.java
- src/main/java/org/assertj/core/error/ShouldHaveCause.java
- src/main/java/org/assertj/core/extractor/ByNameMultipleExtractor.java
- src/main/java/org/assertj/core/extractor/ByNameSingleExtractor.java
- src/main/java/org/assertj/core/groups/Properties.java
- src/main/java/org/assertj/core/internal/Arrays.java
- src/main/java/org/assertj/core/internal/Classes.java
- src/main/java/org/assertj/core/internal/Files.java
- src/main/java/org/assertj/core/internal/Maps.java
- src/main/java/org/assertj/core/internal/Objects.java
- src/main/java/org/assertj/core/internal/OnFieldsComparator.java
- src/main/java/org/assertj/core/internal/Paths.java
- src/main/java/org/assertj/core/internal/StandardComparisonStrategy.java
- src/main/java/org/assertj/core/internal/Urls.java
- src/main/java/org/assertj/core/util/ArrayWrapperList.java
- src/main/java/org/assertj/core/util/DateUtil.java
- src/main/java/org/assertj/core/util/Files.java
- src/main/java/org/assertj/core/util/Strings.java
- src/main/java/org/assertj/core/util/URLs.java
- src/main/java/org/assertj/core/util/diff/Delta.java
- src/main/java/org/assertj/core/util/diff/DiffUtils.java
- src/main/java/org/assertj/core/util/diff/myers/MyersDiff.java
- src/main/java/org/assertj/core/util/introspection/FieldUtils.java
- src/main/java/org/assertj/core/util/introspection/PropertyOrFieldSupport.java
- src/main/java/org/assertj/core/util/introspection/PropertySupport.java
- src/main/java/org/assertj/core/util/xml/XmlStringPrettyFormatter.java
> use Preconditions#checkArgument where possible (2.x part)

- src/main/java/org/assertj/core/internal/Iterables.java
> delete unused Method Iterables#iterableToLookForIsEmpty

- src/main/java/org/assertj/core/api/AbstractIterableAssert.java
- src/main/java/org/assertj/core/api/AbstractLocalDateAssert.java
- src/main/java/org/assertj/core/api/AbstractLocalDateTimeAssert.java
- src/main/java/org/assertj/core/api/AbstractLocalTimeAssert.java
- src/main/java/org/assertj/core/api/AbstractObjectArrayAssert.java
- src/main/java/org/assertj/core/api/AbstractOffsetDateTimeAssert.java
- src/main/java/org/assertj/core/api/AbstractOffsetTimeAssert.java
- src/main/java/org/assertj/core/api/AbstractOptionalAssert.java
- src/main/java/org/assertj/core/api/AbstractZonedDateTimeAssert.java
> use Preconditions#checkArgument where possible (3.x part)

- src/main/java/org/assertj/core/api/AbstractBigDecimalAssert.java
- src/main/java/org/assertj/core/util/Preconditions.java
> minor javadoc fixes

- src/main/java/org/assertj/core/api/AbstractLongArrayAssert.java
- src/main/java/org/assertj/core/data/Percentage.java
- src/main/java/org/assertj/core/util/diff/myers/MyersDiff.java
- src/test/java/org/assertj/core/api/bytearray/ByteArrayAssert_containsExactlyInAnyOrder_with_integers_Test.java
- src/test/java/org/assertj/core/api/floatarray/FloatArrayAssert_containsExactly_Test.java
- src/test/java/org/assertj/core/api/shortarray/ShortArrayAssert_containsExactly_Test.java
- src/test/java/org/assertj/core/error/BasicErrorMessageFactory_create_Test.java
- src/test/java/org/assertj/core/internal/doubles/Doubles_assertEqual_double_with_offset_Test.java
- src/test/java/org/assertj/core/internal/floats/Floats_assertEqual_float_with_offset_Test.java
- src/test/java/org/assertj/core/util/Throwables_getStackTrace_Test.java
> 2.x minor changes/cleanup/javadoc

- pom.xml
.. since we are not using powermock any longer
> get rid of powermock.version

- src/main/java/org/assertj/core/api/AbstractCompletableFutureAssert.java
- src/main/java/org/assertj/core/api/AbstractOptionalDoubleAssert.java
- src/test/java/org/assertj/core/api/Assertions_assertThat_with_Stream_Test.java
> Master only typos

- src/main/java/org/assertj/core/api/AbstractAtomicFieldUpdaterAssert.java
- src/main/java/org/assertj/core/api/AbstractAtomicReferenceAssert.java
- src/main/java/org/assertj/core/api/AtomicIntegerFieldUpdaterAssert.java
- src/main/java/org/assertj/core/api/AtomicLongFieldUpdaterAssert.java
- src/main/java/org/assertj/core/api/AtomicMarkableReferenceAssert.java
- src/main/java/org/assertj/core/api/AtomicReferenceAssert.java
- src/main/java/org/assertj/core/api/AtomicReferenceFieldUpdaterAssert.java
- src/main/java/org/assertj/core/api/AtomicStampedReferenceAssert.java
> Atomic*: added since javadoc

- src/test/java/org/assertj/core/internal/classes/Classes_assertIsInterface_Test.java
- src/test/java/org/assertj/core/internal/objects/Objects_assertIsEqualToIgnoringGivenFields_Test.java
- src/test/java/org/assertj/core/internal/objects/Objects_assertIsEqualToIgnoringNullFields_Test.java
- src/test/java/org/assertj/core/internal/strings/Strings_assertDoesNotMatch_CharSequence_Test.java
- src/test/java/org/assertj/core/internal/strings/Strings_assertEndsWith_Test.java
> unused imports + illegal character warning in javadoc

- src/main/java/org/assertj/core/api/AbstractCompletableFutureAssert.java
- src/main/java/org/assertj/core/api/AbstractLocalDateAssert.java
- src/main/java/org/assertj/core/api/AbstractLocalDateTimeAssert.java
- src/main/java/org/assertj/core/api/AbstractLocalTimeAssert.java
- src/main/java/org/assertj/core/api/AbstractOffsetDateTimeAssert.java
- src/main/java/org/assertj/core/api/AbstractOffsetTimeAssert.java
- src/main/java/org/assertj/core/api/AbstractOptionalAssert.java
- src/main/java/org/assertj/core/api/AbstractOptionalDoubleAssert.java
- src/main/java/org/assertj/core/api/AbstractOptionalIntAssert.java
- src/main/java/org/assertj/core/api/AbstractOptionalLongAssert.java
- src/main/java/org/assertj/core/api/AbstractZonedDateTimeAssert.java
A very first bunch of master-only meaningful generic names.
> Meaningful generic names

- src/main/java/org/assertj/core/api/AbstractBDDSoftAssertions.java
- src/main/java/org/assertj/core/api/AbstractCompletableFutureAssert.java
- src/main/java/org/assertj/core/api/AbstractOptionalAssert.java
- src/main/java/org/assertj/core/api/AbstractStandardSoftAssertions.java
- src/main/java/org/assertj/core/api/Assertions.java
- src/main/java/org/assertj/core/api/AssertionsForClassTypes.java
- src/main/java/org/assertj/core/api/BDDAssertions.java
- src/main/java/org/assertj/core/api/CompletableFutureAssert.java
- src/main/java/org/assertj/core/api/OptionalAssert.java
- src/main/java/org/assertj/core/api/WithAssertions.java
- src/main/java/org/assertj/core/error/OptionalShouldBeEmpty.java
- src/main/java/org/assertj/core/error/OptionalShouldContain.java
some more meaningful generic names: Optional and CompletableFuture
> Meaningful generic names master only

- src/main/java/org/assertj/core/api/AbstractLocalDateAssert.java
- src/main/java/org/assertj/core/api/AbstractLocalDateTimeAssert.java
- src/main/java/org/assertj/core/api/AbstractLocalTimeAssert.java
some minor naming changes + make use of stream
> naming + make use of stream

- pom.xml
> pom.xml: remove empty properties element

- src/main/java/org/assertj/core/api/WithAssertions.java
- src/test/java/org/assertj/core/api/abstract_/AbstractAssert_isInstanceOfSatisfying_Test.java
- src/test/java/org/assertj/core/api/objectarray/ObjectArrayAssert_extracting_Test.java
> meaningful generic name + get rid of unnecessary semicolon

- pom.xml
> pom.xml: remove deactivated animal-sniffer plugin

- src/main/java/org/assertj/core/api/Assertions.java
- src/main/java/org/assertj/core/api/BDDAssertions.java
- src/main/java/org/assertj/core/api/Java6AbstractBDDSoftAssertions.java
- src/main/java/org/assertj/core/api/Java6Assertions.java
- src/main/java/org/assertj/core/api/Java6BDDAssertions.java
It looks like I forgot since javadoc in Assertions in the initial pr.
> since javadoc for Atomic*Assert in *Assertions

- src/main/java/org/assertj/core/api/Java6Assertions.java
- src/main/java/org/assertj/core/api/Java6BDDAssertions.java
It looks like I missed Java6*Assertions in the initial pr.
> added biginteger to java6assertions

- src/main/java/org/assertj/core/api/WithAssertions.java
> replace public static by default

- src/test/java/org/assertj/core/api/atomic/integer/AtomicIntegerAssert_hasNonPositiveValue_Test.java
- src/test/java/org/assertj/core/api/atomic/integer/AtomicIntegerAssert_hasPositiveValue_Test.java
- src/test/java/org/assertj/core/api/atomic/long_/AtomicLongAssert_hasNonPositiveValue_Test.java
- src/test/java/org/assertj/core/api/atomic/long_/AtomicLongAssert_hasPositiveValue_Test.java
> using proper methods in some Tests

- src/main/java/org/assertj/core/error/ShouldOnlyHaveElementsOfTypes.java
- src/main/java/org/assertj/core/internal/Iterables.java
- src/test/java/org/assertj/core/api/atomic/referencearray/AtomicReferenceArrayAssert_hasOnlyElementsOfTypes_Test.java
- src/test/java/org/assertj/core/api/objectarray/ObjectArrayAssert_hasOnlyElementsOfTypes_Test.java
some cleanup for `hasOnlyElementsOfTypes`
> 2.x hasOnlyElementsOfTypes

- pom.xml
In reference to #998, making adjustment here which should hit 3.x (master) eventually.
> [ci] Fix relativePath from pom

- CONTRIBUTING.md
Intellij users needs the Eclipse Code Formatter Plugin to import custom formatter xml
> Added hint in Contribute-Readme

- src/main/java/org/assertj/core/api/AbstractIterableAssert.java
- src/main/java/org/assertj/core/api/AbstractObjectArrayAssert.java
- src/main/java/org/assertj/core/api/AtomicReferenceArrayAssert.java
- src/main/java/org/assertj/core/api/ObjectEnumerableAssert.java
- src/test/java/org/assertj/core/api/atomic/referencearray/AtomicReferenceArrayAssert_containsExactlyInAnyOrderElementsOf_Test.java
- src/test/java/org/assertj/core/api/atomic/referencearray/AtomicReferenceArrayAssert_usingFieldByFieldElementComparator_Test.java
- src/test/java/org/assertj/core/api/iterable/IterableAssert_containsExactlyInAnyOrderElementsOf_Test.java
- src/test/java/org/assertj/core/api/iterable/IterableAssert_usingFieldByFieldElementComparator_Test.java
- src/test/java/org/assertj/core/api/objectarray/ObjectArrayAssert_containsExactlyInAnyOrderElementsOf_Test.java
- src/test/java/org/assertj/core/api/objectarray/ObjectArrayAssert_usingFieldByFieldElementComparator_Test.java
> add ObjectEnumarableAssert#containsExactlyInAnyOrderElementsOf

- src/main/java/org/assertj/core/util/DoubleComparator.java
- src/main/java/org/assertj/core/util/FloatComparator.java
- src/main/java/org/assertj/core/util/NullSafeComparator.java
- src/test/java/org/assertj/core/api/objectarray/ObjectArrayAssert_containsExactlyInAnyOrderElementsOf_Test.java
- src/test/java/org/assertj/core/util/DoubleComparatorTest.java
- src/test/java/org/assertj/core/util/FloatComparatorTest.java
> Improved handling of null at float and double comparators (#1015)

- src/main/java/org/assertj/core/api/AbstractThrowableAssert.java
- src/main/java/org/assertj/core/api/Descriptable.java
- src/main/java/org/assertj/core/api/ThrowableAssertAlternative.java
- src/main/java/org/assertj/core/api/ThrowableTypeAssert.java
- src/test/java/org/assertj/core/api/Assertions_assertThat_with_Throwable_Test.java
- src/test/java/org/assertj/core/api/throwable/ExpectThrowableAssert_isThrownBy_Test.java
- src/test/java/org/assertj/core/api/throwable/ThrowableAssert_built_from_ThrowingCallable_Test.java
- src/test/java/org/assertj/core/api/throwable/ThrowableAssert_built_from_lambda_Test.java
- src/test/java/org/assertj/core/api/throwable/ThrowableAssert_built_with_then_method_Test.java
- src/test/java/org/assertj/core/api/throwable/ThrowableTypeAssert_description_Test.java
> Added assertion description to throwable type assert (#1007)

- .travis.yml
> [travis] Add openjdk8

- src/main/java/org/assertj/core/error/uri/ShouldHaveParameter.java
- src/main/java/org/assertj/core/internal/Maps.java
- src/main/java/org/assertj/core/util/Files.java
- src/main/java/org/assertj/core/util/TextFileWriter.java
- src/main/java/org/assertj/core/util/URLs.java
- Replace try-close with try-with-resources
- Other minor code improvements and refactor
* Fixes: Non-issue related PR
* Javadoc with a code example (API only) : Not needed
> Code polish and fix sonar issues

- src/main/java/org/assertj/core/api/ObjectEnumerableAssert.java
> Update java docs for containsOnly and containsOnlyElementsOf (#1075)

- .travis.yml
* Fixes: sonarcloud configuration
* Javadoc with a code example (API only) : Not needed
> Sonarcloud ci master

- src/main/java/org/assertj/core/error/ShouldContainCharSequenceOnlyOnce.java
Tiny refactoring, exploiting method overloading.
> Refactoring ShouldContainCharSequenceOnlyOnce

- src/main/java/org/assertj/core/api/AbstractDoubleAssert.java
- src/main/java/org/assertj/core/api/AbstractFloatAssert.java
- src/main/java/org/assertj/core/api/AbstractIntegerAssert.java
- src/main/java/org/assertj/core/api/AbstractLongAssert.java
- src/main/java/org/assertj/core/api/AbstractShortAssert.java
> 1117 add isBetween and isStrictlyBetween doc

- src/main/java/org/assertj/core/api/ObjectEnumerableAssert.java
- src/main/java/org/assertj/core/api/SoftAssertions.java
- src/main/java/org/assertj/core/error/ShouldBeSorted.java
- src/main/java/org/assertj/core/internal/Iterables.java
- src/main/java/org/assertj/core/internal/StandardComparisonStrategy.java
- src/main/java/org/assertj/core/internal/TypeComparators.java
- src/main/java/org/assertj/core/util/diff/myers/MyersDiff.java
- src/test/java/org/assertj/core/api/ClassAssertBaseTest.java
- src/test/java/org/assertj/core/api/iterable/IterableAssert_flatExtracting_with_multiple_extractors_Test.java
- src/test/java/org/assertj/core/data/Offset_built_with_Long_Test.java
- src/test/java/org/assertj/core/data/TolkienCharacter.java
- src/test/java/org/assertj/core/description/Description_toString_Test.java
- src/test/java/org/assertj/core/internal/ClassesBaseTest.java
- src/test/java/org/assertj/core/internal/classes/Classes_assertContainsAnnotation_Test.java
* Fixes 
* Unit tests : NO 
Simple code clean.
> Clean code

- pom.xml
See https://github.com/marschall/memoryfilesystem/milestone/32?closed=1 for changes in v1.1.0
> update memoryfilesystem to v1.1.0

- src/main/java/org/assertj/core/api/AbstractIterableAssert.java
- src/main/java/org/assertj/core/util/Arrays.java
- src/main/java/org/assertj/core/util/Strings.java
> fix some minor typos in javadoc

- src/test/java/org/assertj/core/api/abstract_/AbstractAssert_isIn_with_Iterable_Test.java
- src/test/java/org/assertj/core/api/iterable/IterableAssert_filteredOn_predicate_Test.java
- src/test/java/org/assertj/core/api/object/ObjectAssert_hasNoNullFieldsOrProperties_Test.java
- src/test/java/org/assertj/core/internal/files/Files_assertHasBinaryContent_Test.java
- src/test/java/org/assertj/core/internal/iterables/Iterables_assertAreNot_Test.java
- src/test/java/org/assertj/core/internal/iterables/Iterables_assertAre_Test.java
- src/test/java/org/assertj/core/internal/iterables/Iterables_assertDoNotHave_Test.java
- src/test/java/org/assertj/core/internal/iterables/Iterables_assertHave_Test.java
- src/test/java/org/assertj/core/internal/lists/List_assertIs_Test.java
- src/test/java/org/assertj/core/internal/maps/Maps_assertContains_Test.java
- src/test/java/org/assertj/core/internal/objectarrays/ObjectArrays_assertAreAtMost_Test.java
- src/test/java/org/assertj/core/internal/objectarrays/ObjectArrays_assertAreExactly_Test.java
- src/test/java/org/assertj/core/internal/objectarrays/ObjectArrays_assertAreNot_Test.java
- src/test/java/org/assertj/core/internal/objectarrays/ObjectArrays_assertAre_Test.java
- src/test/java/org/assertj/core/internal/objectarrays/ObjectArrays_assertDoNotHave_Test.java
- src/test/java/org/assertj/core/internal/objectarrays/ObjectArrays_assertHaveAtLeast_Test.java
- src/test/java/org/assertj/core/internal/objectarrays/ObjectArrays_assertHaveAtMost_Test.java
- src/test/java/org/assertj/core/internal/objectarrays/ObjectArrays_assertHaveExactly_Test.java
- src/test/java/org/assertj/core/internal/objectarrays/ObjectArrays_assertHaveNot_Test.java
- src/test/java/org/assertj/core/internal/objectarrays/ObjectArrays_assertHave_Test.java
- src/test/java/org/assertj/core/internal/shortarrays/ShortArrays_assertHasSameSizeAs_with_Iterable_Test.java
- src/test/java/org/assertj/core/internal/shortarrays/ShortArrays_assertIsSorted_Test.java
> minor javadoc fixes in test src

- .mvn/wrapper/maven-wrapper.properties
- .travis.yml
> travis: use maven wrapper

- src/main/java/org/assertj/core/error/ShouldBeEqualByComparingFieldByFieldRecursively.java
- src/test/java/org/assertj/core/error/ShouldBeEqualByComparingFieldByFieldRecursively_create_Test.java
> Bugfix/1145 comparing field by field recursively npe fix 2.x

- pom.xml
> Adding assertj-core as Automatic-Module-Name in Manifest file.

- src/main/java/org/assertj/core/data/Offset.java
- src/main/java/org/assertj/core/error/ShouldBeEqualWithinOffset.java
* Fixes: NA
* Unit tests: NA
* Javadoc with a code example (API only): NA
> Offset JavaDoc: fix fail/pass condition pseudo code

- README.md
Does not look good, should be removed (or fixed).
> README.md: Remove dead code coverage link

- .travis.yml
> Travis: Use Java 11 supplied by travis (simplifies .travis.yml)

- src/main/java/org/assertj/core/api/AbstractZonedDateTimeAssert.java
Fixes a documentation copy-paste error
> Fix copy paste error in description

- src/test/java/org/assertj/core/error/ShouldBeEqual_newAssertionError_Test.java
- src/test/java/org/assertj/core/internal/strings/Strings_assertBlank_Test.java
- src/test/java/org/assertj/core/internal/strings/Strings_assertContainsOnlyWhitespaces_Test.java
- src/test/java/org/assertj/core/internal/strings/Strings_assertContainsWhitespaces_Test.java
- src/test/java/org/assertj/core/internal/strings/Strings_assertDoesNotContainAnyWhitespaces_Test.java
- src/test/java/org/assertj/core/internal/strings/Strings_assertDoesNotContainOnlyWhitespaces_Test.java
- src/test/java/org/assertj/core/internal/strings/Strings_assertJavaBlank_Test.java
- src/test/java/org/assertj/core/internal/strings/Strings_assertNotBlank_Test.java
- src/test/java/org/assertj/core/internal/strings/Strings_assertNotJavaBlank_Test.java
a minor cleanup of some junit jupiter parameterized tests
> Get rid of Arguments usage if possible

- src/test/java/org/assertj/core/api/Assertions_assertThat_with_Stream_startsWith_Test.java
- src/test/java/org/assertj/core/api/Assertions_assertThat_with_primitive_int_Test.java
- src/test/java/org/assertj/core/api/assumptions/Class_final_method_assertions_in_assumptions_Test.java
- src/test/java/org/assertj/core/api/assumptions/Iterator_assumptions_Test.java
- src/test/java/org/assertj/core/api/assumptions/List_special_assertion_methods_in_assumptions_Test.java
- src/test/java/org/assertj/core/api/assumptions/Map_special_assertion_methods_in_assumptions_Test.java
- src/test/java/org/assertj/core/api/assumptions/ObjectArray_special_assertion_methods_in_assumptions_Test.java
- src/test/java/org/assertj/core/api/assumptions/Object_special_assertion_methods_in_assumptions_Test.java
Some minor things I stumbled over recently, see commit messages for details.
> Cleanup test code

- src/test/java/org/assertj/core/api/abstract_/AbstractAssert_satisfies_with_Condition_Test.java
... since we are using junit jupiter now.
> Use @BeforeAll instead of @BeforeClass

- pom.xml
see [junit 5.3.1](https://junit.org/junit5/docs/5.3.1/release-notes/) and [opentest4j 1.1.1](https://github.com/ota4j-team/opentest4j/milestone/5?closed=1) release notes.
> Update JUnit to 5.3.1 and opentest4j to 1.1.1

- pom.xml
PR created to check whether builds are passing on different JDKs
> Bump maven-bundle-plugin version to 4.1.0

- src/main/scripts/convert-junit5-assertions-to-assertj-on-osx.sh
provides OSX script for JUnit5 -> AssertJ migration
more info at http://testinglikeaboss.com/tips-tricks/migrating-from-junit-5-assertions-to-assertj/
> #1350 junit5 migration script for osx

- src/test/java/org/assertj/core/internal/throwables/Throwables_assertHasCause_Test.java
Refactoring of hasCause tests, as promised... I didn't parameters the "passing" ones as there were only 2.
> Refactor hasCause tests

- .travis.yml
> Travis: Build with Java 12 and 13

- src/main/java/org/assertj/core/api/AbstractObjectArrayAssert.java
- src/main/java/org/assertj/core/internal/Iterables.java
> fix some typos

- src/main/java/org/assertj/core/api/AbstractAssert.java
- src/main/java/org/assertj/core/api/AbstractMapAssert.java
let's add some more @since 3.12.0.
> Add missing @since 3.12.0

- pom.xml
- src/test/java/org/assertj/core/api/assumptions/Assumptions_assumeThat_Atomics_Test.java
- src/test/java/org/assertj/core/api/assumptions/Assumptions_assumeThat_Numbers_Test.java
- src/test/java/org/assertj/core/api/assumptions/Assumptions_assumeThat_with_various_java_8_types_Test.java
- src/test/java/org/assertj/core/api/assumptions/Assumptions_assumeThat_with_various_types_Test.java
- src/test/java/org/assertj/core/api/assumptions/BaseAssumptionRunner.java
- src/test/java/org/assertj/core/api/assumptions/Class_final_method_assertions_in_assumptions_Test.java
- src/test/java/org/assertj/core/api/assumptions/Iterable_special_assertion_methods_in_assumptions_Test.java
- src/test/java/org/assertj/core/api/assumptions/List_special_assertion_methods_in_assumptions_Test.java
- src/test/java/org/assertj/core/api/assumptions/Map_special_assertion_methods_in_assumptions_Test.java
- src/test/java/org/assertj/core/api/assumptions/ObjectArray_special_assertion_methods_in_assumptions_Test.java
- src/test/java/org/assertj/core/api/assumptions/Object_special_assertion_methods_in_assumptions_Test.java
- src/test/java/org/assertj/core/api/assumptions/Predicate_final_method_assertions_in_assumptions_Test.java
- src/test/java/org/assertj/core/api/throwable/ThrowableTypeAssert_description_Test.java
see [release notes](https://junit.org/junit5/docs/5.4.0/release-notes/) for details.
> Update JUnit to version 5.4.0

- src/main/java/org/assertj/core/api/JUnitJupiterBDDSoftAssertions.java
- src/main/java/org/assertj/core/api/MapAssert.java
- src/test/java/org/assertj/core/api/Assertions_fail_Test.java
- src/test/java/org/assertj/core/api/JUnitBDDSoftAssertionsFailureTest.java
- src/test/java/org/assertj/core/api/JUnitBDDSoftAssertionsSuccessTest.java
- src/test/java/org/assertj/core/api/JUnitJupiterBDDSoftAssertionsSuccessTest.java
- src/test/java/org/assertj/core/api/JUnitJupiterSoftAssertionsSuccessTest.java
- src/test/java/org/assertj/core/api/JUnitSoftAssertionsFailureTest.java
- src/test/java/org/assertj/core/api/JUnitSoftAssertionsSuccessTest.java
- src/test/java/org/assertj/core/api/Java6JUnitBDDSoftAssertionsSuccessTest.java
- src/test/java/org/assertj/core/api/Java6JUnitSoftAssertionsSuccessTest.java
- src/test/java/org/assertj/core/api/assumptions/Assumptions_assumeThat_Atomics_Test.java
- src/test/java/org/assertj/core/api/assumptions/Assumptions_assumeThat_with_various_types_Test.java
- src/test/java/org/assertj/core/error/ShouldBeEqual_Test.java
- src/test/java/org/assertj/core/error/ShouldBeExhausted_create_Test.java
- src/test/java/org/assertj/core/error/ShouldHaveNext_create_Test.java
- src/test/java/org/assertj/core/internal/Digests_digestDiff_Test.java
- src/test/java/org/assertj/core/internal/files/Files_assertSameContentAs_Test.java
- src/test/java/org/assertj/core/internal/urls/Uris_assertHasFragment_Test.java
- src/test/java/org/assertj/core/internal/urls/Urls_assertHasAnchor_Test.java
- src/test/java/org/assertj/core/internal/urls/Urls_assertHasPath_Test.java
- src/test/java/org/assertj/core/test/TypeCanonizerTest.java
- src/test/java/org/assertj/core/util/URLs_contentOf_Test.java
- src/test/java/org/assertj/core/util/URLs_linesOf_Test.java
some minor things I stumbled over recently.
> minor cleanup

- src/main/java/org/assertj/core/extractor/ToStringExtractor.java
- src/test/java/org/assertj/core/api/objectarray/ObjectArrayAssert_areAtLeast_Test.java
- src/test/java/org/assertj/core/api/objectarray/ObjectArrayAssert_areAtMost_Test.java
- src/test/java/org/assertj/core/api/objectarray/ObjectArrayAssert_areExactly_Test.java
- src/test/java/org/assertj/core/api/objectarray/ObjectArrayAssert_filteredOnAssertions_Test.java
- src/test/java/org/assertj/core/api/objectarray/ObjectArrayAssert_filteredOn_predicate_Test.java
- src/test/java/org/assertj/core/api/objectarray/ObjectArrayAssert_haveAtLeast_Test.java
- src/test/java/org/assertj/core/api/objectarray/ObjectArrayAssert_haveAtMost_Test.java
- src/test/java/org/assertj/core/api/objectarray/ObjectArrayAssert_haveExactly_Test.java
Get rid of not needed doc/duplicate license header and fix some javadoc errors
> Javadoc fixes

- src/test/java/org/assertj/core/api/iterable/IterableAssert_areAtLeast_Test.java
- src/test/java/org/assertj/core/api/iterable/IterableAssert_areAtMost_Test.java
- src/test/java/org/assertj/core/api/iterable/IterableAssert_areExactly_Test.java
- src/test/java/org/assertj/core/api/iterable/IterableAssert_haveAtLeast_Test.java
- src/test/java/org/assertj/core/api/iterable/IterableAssert_haveAtMost_Test.java
- src/test/java/org/assertj/core/api/iterable/IterableAssert_haveExactly_Test.java
... which I stumbled over recently.
> fix some more javadoc errors

- src/test/java/org/assertj/core/internal/bigdecimals/BigDecimals_assertIsCloseTo_Test.java
- src/test/java/org/assertj/core/internal/bigintegers/BigIntegers_assertIsCloseTo_Test.java
- src/test/java/org/assertj/core/internal/doubles/Doubles_assertIsCloseTo_Test.java
- src/test/java/org/assertj/core/internal/floats/Floats_assertIsCloseTo_Test.java
> fix a minor typo

- pom.xml
see [release notes](https://junit.org/junit5/docs/5.4.1/release-notes/) for details.
> Update JUnit to version 5.4.1

- .gitignore
- .mvn/wrapper/MavenWrapperDownloader.java
- .mvn/wrapper/maven-wrapper.properties
- mvnw
- mvnw.cmd
> Update maven wrapper to 0.5.3

- src/main/java/org/assertj/core/api/ExtensionPoints.java
> correct  Javadoc typo #1489

- src/main/java/org/assertj/core/api/AbstractDateAssert.java
- src/main/java/org/assertj/core/internal/Dates.java
- src/test/java/org/assertj/core/api/date/DateAssert_isAfterOrEqualTo_Test.java
- src/test/java/org/assertj/core/api/date/DateAssert_isBeforeOrEqualTo_Test.java
- src/test/java/org/assertj/core/internal/dates/Dates_assertIsAfterOrEqualTo_Test.java
- src/test/java/org/assertj/core/internal/dates/Dates_assertIsBeforeOrEqualTo_Test.java
> Rename methods isBeforeOrEqualsTo and isAfterOrEqualsTo

- src/main/java/org/assertj/core/api/AbstractDateAssert.java
- src/main/java/org/assertj/core/api/AbstractInstantAssert.java
- src/main/java/org/assertj/core/api/AbstractLocalDateAssert.java
- src/main/java/org/assertj/core/api/AbstractLocalDateTimeAssert.java
- src/main/java/org/assertj/core/api/AbstractLocalTimeAssert.java
- src/main/java/org/assertj/core/api/AbstractOffsetDateTimeAssert.java
- src/main/java/org/assertj/core/api/AbstractOffsetTimeAssert.java
- src/main/java/org/assertj/core/api/AbstractZonedDateTimeAssert.java
- src/main/java/org/assertj/core/error/ShouldBeAfterOrEqualTo.java
- src/main/java/org/assertj/core/error/ShouldBeBeforeOrEqualTo.java
- src/main/java/org/assertj/core/internal/Dates.java
- src/test/java/org/assertj/core/api/date/DateAssert_isAfterOrEqualTo_Test.java
- src/test/java/org/assertj/core/api/instant/InstantAssert_IsBeforeOrEqualTo_Test.java
- src/test/java/org/assertj/core/api/instant/InstantAssert_isAfterOrEqual_Test.java
- src/test/java/org/assertj/core/api/localdate/LocalDateAssert_isAfterOrEqualTo_Test.java
- src/test/java/org/assertj/core/api/localdate/LocalDateAssert_isBeforeOrEqualTo_Test.java
- src/test/java/org/assertj/core/api/localdatetime/LocalDateTimeAssert_isAfterOrEqualTo_Test.java
- src/test/java/org/assertj/core/api/localdatetime/LocalDateTimeAssert_isBeforeOrEqualTo_Test.java
- src/test/java/org/assertj/core/api/localtime/LocalTimeAssert_isAfterOrEqualTo_Test.java
- src/test/java/org/assertj/core/api/localtime/LocalTimeAssert_isBeforeOrEqualTo_Test.java
- src/test/java/org/assertj/core/api/offsetdatetime/OffsetDateTimeAssert_isAfterOrEqualTo_Test.java
- src/test/java/org/assertj/core/api/offsetdatetime/OffsetDateTimeAssert_isBeforeOrEqualTo_Test.java
- src/test/java/org/assertj/core/api/offsettime/OffsetTimeAssert_isAfterOrEqualTo_Test.java
- src/test/java/org/assertj/core/api/offsettime/OffsetTimeAssert_isBeforeOrEqualTo_Test.java
- src/test/java/org/assertj/core/api/zoneddatetime/ZonedDateTimeAssert_isAfterOrEqualTo_Test.java
- src/test/java/org/assertj/core/api/zoneddatetime/ZonedDateTimeAssert_isBeforeOrEqualTo_Test.java
- src/test/java/org/assertj/core/error/ShouldBeAfterOrEqualTo_create_Test.java
- src/test/java/org/assertj/core/error/ShouldBeBeforeOrEqualTo_create_Test.java
- src/test/java/org/assertj/core/internal/dates/Dates_assertIsAfterOrEqualTo_Test.java
- src/test/java/org/assertj/core/internal/dates/Dates_assertIsBeforeOrEqualTo_Test.java
> Fix typo in error message factories (#1506)

- src/main/java9/module-info.java
> Add missing `uses` directives to module descriptor

- pom.xml
> Update JUnit to version 5.5.0.

- src/main/java/org/assertj/core/api/InstanceOfAssertFactories.java
- src/test/java/org/assertj/core/api/InstanceOfAssertFactoriesTest.java
> Add TYPE suffix to URI and URL factories to prevent shadowing

- src/main/java/org/assertj/core/error/ConstructorInvoker.java
> ConstructorInvoker: Delete unnecessary and unused code

- src/main/java/org/assertj/core/error/ShouldHaveMessage.java
- src/test/java/org/assertj/core/error/ShouldHaveMessage_create_Test.java
> fix possible MissingFormatArgumentException in ShouldHaveMessage

- src/main/java/org/assertj/core/internal/Strings.java
- src/test/java/org/assertj/core/internal/strings/Strings_assertHasSizeBetween_Test.java
> assertHasSizeBetween works with strings. Fixes #1586

- src/main/java/org/assertj/core/api/AbstractObjectAssert.java
- src/main/java/org/assertj/core/api/Assertions.java
- src/main/java/org/assertj/core/api/WithAssertions.java
- src/test/java/org/assertj/core/api/Assertions_as_with_InstanceOfAssertFactory_Test.java
- src/test/java/org/assertj/core/api/Assertions_from_with_Function_Test.java
- src/test/java/org/assertj/core/api/SoftAssertionsTest.java
- src/test/java/org/assertj/core/api/WithAssertions_delegation_Test.java
- src/test/java/org/assertj/core/api/assumptions/Object_special_assertion_methods_in_assumptions_Test.java
Also PR for release notes: assertj/doc#18
* Fixes N/A
> Add as(InstanceOfAssertFactory) to Assertions for readability

- CONTRIBUTING.md
- src/test/java/org/assertj/core/api/optional/OptionalAssert_containsInstanceOf_Test.java
Also small reordering to keep the same topics closer
> Add `then` and `package-private` info to contribution guidelines

- src/main/java/org/assertj/core/api/SoftProxies.java
- src/test/java/org/assertj/core/api/SoftAssertionsTest.java
* Fixes #1628
Release notes PR: assertj/doc#20
> Add SoftAssertions proxying for get() of AbstractOptionalAssert

- src/main/java/org/assertj/core/api/AbstractIterableAssert.java
- src/main/java/org/assertj/core/api/AbstractOptionalAssert.java
- src/main/java/org/assertj/core/api/Assertions.java
- src/test/java/org/assertj/core/api/BDDSoftAssertionsTest.java
- src/test/java/org/assertj/core/api/SoftAssertionsTest.java
- src/test/java/org/assertj/core/api/assumptions/Assumptions_assumeThat_involving_iterable_navigation_Test.java
- src/test/java/org/assertj/core/api/iterable/IterableAssert_first_Test.java
- src/test/java/org/assertj/core/api/iterable/IterableAssert_first_with_InstanceOfAssertFactory_Test.java
- src/test/java/org/assertj/core/api/optional/OptionalAssert_get_with_InstanceOfAssertFactory_Test.java
> Add first(InstanceOfAssertFactory) to AbstractIterableAssert

- src/main/java/org/assertj/core/api/AbstractIterableAssert.java
- src/main/java/org/assertj/core/api/Assertions.java
- src/test/java/org/assertj/core/api/BDDSoftAssertionsTest.java
- src/test/java/org/assertj/core/api/SoftAssertionsTest.java
- src/test/java/org/assertj/core/api/assumptions/Assumptions_assumeThat_involving_iterable_navigation_Test.java
- src/test/java/org/assertj/core/api/iterable/IterableAssert_last_Test.java
- src/test/java/org/assertj/core/api/iterable/IterableAssert_last_with_InstanceOfAssertFactory_Test.java
> Add last(InstanceOfAssertFactory) to AbstractIterableAssert

- src/main/java/org/assertj/core/api/Java6AbstractStandardSoftAssertions.java
> Fix abstract modified for Java6AbstractStandardSoftAssertions

- CONTRIBUTING.md
- src/test/java/org/assertj/core/api/optional/OptionalAssert_containsInstanceOf_Test.java
Follow up on b581c9e98e0801dfe5076f177d609c3c7ddfd416
> Add combined WHEN/THEN example to contribution guidelines

- .mvn/wrapper/MavenWrapperDownloader.java
- .mvn/wrapper/maven-wrapper.properties
- mvnw
- mvnw.cmd
> [mvn] Bump maven wrapper to 0.5.6

- src/main/java/org/assertj/core/api/AbstractClassAssert.java
- src/main/java/org/assertj/core/error/ShouldHaveAnnotations.java
- src/main/java/org/assertj/core/error/ShouldHaveSuperclass.java
- src/main/java/org/assertj/core/internal/Classes.java
- src/test/java/org/assertj/core/api/classes/ClassAssert_hasSuperclass_Test.java
- src/test/java/org/assertj/core/error/ShouldHaveSuperclass_create_Test.java
- src/test/java/org/assertj/core/internal/classes/Classes_assertHasSuperclass_Test.java
- src/test/java/org/assertj/core/internal/classes/Classes_assertIsPackagePrivate_Test.java
> Add hasSuperclass(Class<?>) to AbstractClassAssert

- src/main/java/org/assertj/core/api/filter/NotFilter.java
- src/main/java/org/assertj/core/api/recursive/comparison/DualValue.java
- src/main/java/org/assertj/core/util/introspection/MemberUtils.java
> Removes unused methods.

- .travis.yml
- src/test/java/org/assertj/core/internal/classes/Classes_assertHasMethods_Test.java
> Travis: Add OpenJDK 14 build (openjdk-ea now uses OpenJDK 15).

- src/main/java/org/assertj/core/error/ClassModifierShouldBe.java
- src/test/java/org/assertj/core/error/ClassModifierShouldBe_create_Test.java
> Fix trailing space when class is only package-private

- src/main/java/org/assertj/core/extractor/ByNameMultipleExtractor.java
- src/main/java/org/assertj/core/extractor/ByNameSingleExtractor.java
- src/main/java/org/assertj/core/extractor/Extractors.java
- src/main/java/org/assertj/core/extractor/ResultOfExtractor.java
- src/main/java/org/assertj/core/extractor/ToStringExtractor.java
- src/test/java/org/assertj/core/extractor/ByNameMultipleExtractorTest.java
- src/test/java/org/assertj/core/extractor/ByNameSingleExtractorTest.java
- src/test/java/org/assertj/core/extractor/ToStringExtractorTest.java
- src/test/java/org/assertj/core/test/Maps.java
Also reduced visibility wherever possible and refactored the tests with BDD style.
* Fixes N/A
> Remove unnecessary type parameters from extractors

- .github/workflows/cross-version.yml
> Use Java 14 final release and drop Java 13 build.

- .github/workflows/cross-version.yml
- .github/workflows/main.yml
> Cache maven repository to speed-up github actions builds.

- src/main/java/org/assertj/core/api/ErrorCollector.java
> Fix issue #1879: allow failures to be recorded from multiple threads

- src/main/java/org/assertj/core/api/SoftProxies.java
We use a composite class loader for defining soft proxies when the
assert class is from a different class loader than the AssertJ classes.
This can occur in OSGi when the assert class is from a bundle. The
composite class loader provides access to the internal, non-exported
types of AssertJ. ByteBuddy will define the proxy class in the
CompositeClassLoader rather than in the class loader of the assert
class. This means the assert class cannot assume package private access
to super types, interfaces, etc. since the proxy class is defined in a
different class loader (the CompositeClassLoader) than the assert class.
Fixes https://github.com/joel-costigliola/assertj-core/issues/1964
> Better handle soft proxies for custom assert classes in OSGi bundles

- src/main/java/org/assertj/core/util/introspection/Introspection.java
Second iteration of https://github.com/joel-costigliola/assertj-core/pull/1973
Only introduces method cache w/o changing comparison algorithm
> Speed up reflective comparison

- pom.xml
> Bump jacoco-maven-plugin from 0.8.5 to 0.8.6

- pom.xml
- src/it/junit4-with-opentest4j/pom.xml
- src/it/junit4-with-opentest4j/src/test/java/maven/invoker/it/assumptions/JUnit4_with_opentest4j_Test.java
- src/it/settings.xml
- src/it/setup/invoker.properties
- src/it/setup/pom.xml
- src/it/testng-with-junit4/pom.xml
- src/it/testng-with-junit4/src/test/java/maven/invoker/it/assumptions/TestNG_with_JUnit4_Test.java
This covers the cases mentioned in #1961 and #1985. Any other relevant use case to cover?
> Add assumptions it tests

- src/test/java/org/assertj/core/api/junit/jupiter/SoftAssertionsExtension_PER_CLASS_Concurrency_Test.java
Attempted fix for #1996
Make the hashmap synchronized. Add better check & reporting for null.
> Attempted fix for flaky test

- src/main/java/org/assertj/core/error/AnyElementShouldMatch.java
- src/test/java/org/assertj/core/error/AnyElementsShouldMatch_create_Test.java
* Fixes: Removed <> from AnyElementShouldMatch
* Javadoc with a code example (on API only) :  NA
> Remove <> from AnyElementShouldMatch

- src/main/java/org/assertj/core/error/GroupTypeDescription.java
- src/main/java/org/assertj/core/error/ShouldContain.java
- src/main/java/org/assertj/core/internal/Iterables.java
- src/test/java/org/assertj/core/error/GroupTypeDescription_getGroupTypeDescription_Test.java
- src/test/java/org/assertj/core/internal/iterables/Iterables_assertContainsAll_Test.java
- src/test/java/org/assertj/core/internal/iterables/Iterables_assertContains_Test.java
> #2132 Wrong error message in assertion when using Set collection

- src/main/java/org/assertj/core/api/AbstractDoubleAssert.java
- src/main/java/org/assertj/core/api/AbstractFloatAssert.java
- src/main/java/org/assertj/core/api/FloatingPointNumberAssert.java
- src/main/java/org/assertj/core/error/ShouldNotBeFinite.java
- src/main/java/org/assertj/core/error/ShouldNotBeInfinite.java
- src/main/java/org/assertj/core/internal/Doubles.java
- src/main/java/org/assertj/core/internal/Floats.java
- src/main/java/org/assertj/core/internal/RealNumbers.java
- src/test/java/org/assertj/core/api/double_/DoubleAssert_isNotFinite_Test.java
- src/test/java/org/assertj/core/api/double_/DoubleAssert_isNotInfinite_Test.java
- src/test/java/org/assertj/core/api/float_/FloatAssert_isNotFinite_Test.java
- src/test/java/org/assertj/core/api/float_/FloatAssert_isNotInfinite_Test.java
- src/test/java/org/assertj/core/error/ShouldNotBeFinite_create_Test.java
- src/test/java/org/assertj/core/error/ShouldNotBeInfinite_create_Test.java
- src/test/java/org/assertj/core/internal/doubles/Doubles_assertIsInfinite_Test.java
- src/test/java/org/assertj/core/internal/doubles/Doubles_assertIsNotFinite_Test.java
- src/test/java/org/assertj/core/internal/doubles/Doubles_assertIsNotInfinite_Test.java
- src/test/java/org/assertj/core/internal/floats/Floats_assertIsFinite_Test.java
- src/test/java/org/assertj/core/internal/floats/Floats_assertIsNotFinite_Test.java
- src/test/java/org/assertj/core/internal/floats/Floats_assertIsNotInfinite_Test.java
> Add isNotFinite and isNotInfinite assertions for float and double

- src/main/java/org/assertj/core/condition/MappedCondition.java
- src/test/java/org/assertj/core/condition/MappedConditionTest.java
> Add Mapped Condition

- pom.xml
* Fixes NA
* Unit tests :  NA
* Javadoc with a code example (on API only) :  NA
It looks like project to build require `java 11` at least, so check this requirement at the build beginning can help - especially for new contributors.
> Check java version during build

- src/main/java/org/assertj/core/condition/MappedCondition.java
- src/main/java/org/assertj/core/condition/VerboseCondition.java
- src/test/java/org/assertj/core/condition/VerboseConditionTest.java
Signed-off-by: Stefan Bischof <stbischof@bipolis.org>
> Add VerboseCondition for more verbose descriptions

- src/main/java/org/assertj/core/api/RecursiveComparisonAssert.java
Just a minor fix for the docs.
> improve javadoc

- src/main/java/org/assertj/core/configuration/PreferredAssumptionException.java
> Drop `if` check in favor of overridden methods

- src/main/java/org/assertj/core/api/AbstractCharSequenceAssert.java
- src/main/java/org/assertj/core/error/ShouldBeMixedCase.java
- src/main/java/org/assertj/core/internal/Strings.java
- src/test/java/org/assertj/core/api/charsequence/CharSequenceAssert_isMixedCase_Test.java
- src/test/java/org/assertj/core/error/ShouldBeLowerCase_create_Test.java
- src/test/java/org/assertj/core/error/ShouldBeMixedCase_create_Test.java
- src/test/java/org/assertj/core/internal/strings/Strings_assertIsLowerCase_Test.java
- src/test/java/org/assertj/core/internal/strings/Strings_assertIsMixedCase_Test.java
- src/test/java/org/assertj/core/internal/strings/Strings_assertIsUpperCase_Test.java
> #2239 added AbstractCharSequenceAssert.isMixedCase method

- src/main/java/org/assertj/core/internal/Classes.java
- src/test/java/org/assertj/core/internal/classes/Classes_assertHasMethods_Test.java
> Add default method lookup to `hasMethods`

- src/main/java/org/assertj/core/api/AbstractCollectionAssert.java
- src/main/java/org/assertj/core/error/ShouldBeUnmodifiable.java
- src/test/java/org/assertj/core/api/collection/CollectionAssert_isUnmodifiable_Test.java
- src/test/java/org/assertj/core/error/ShouldBeUnmodifiableTest.java
> Add `isUnmodifiable` to `Collection` assertions

- src/main/java/org/assertj/core/presentation/StandardRepresentation.java
- src/test/java/org/assertj/core/presentation/StandardRepresentation_toStringOf_Test.java
> Improve `Class` representation for anonymous and local types

- src/main/java/org/assertj/core/api/AbstractUriAssert.java
> Add Comparable assertions for URI #2487

- pom.xml
- verify.bndrun
> Remove Byte Buddy shading

- src/main/java/org/assertj/core/api/AbstractObjectArrayAssert.java
Fixed an error in javadoc.
* Unit tests : NA 
> Fix error in javadoc @see

- src/main/java/org/assertj/core/api/ComparatorFactory.java
Removing those unnecessary unboxing makes the clode cleaner, which only beneftis in the long term the project.
> Removed unnecessary unboxing in `ComparatorFactory`.

- src/main/java/org/assertj/core/api/AbstractSoftAssertions.java
- src/main/java/org/assertj/core/api/Assertions.java
- src/main/java/org/assertj/core/api/BDDAssertions.java
- src/main/java/org/assertj/core/api/Fail.java
- src/main/java/org/assertj/core/api/WithAssertions.java
- src/test/java/org/assertj/core/api/fail/Fail_fail_withMessageAsLambda_Test.java
> Updated docs describing passing Fail.fail() as a lambda

- src/test/java/org/assertj/core/api/integer_/IntegerAssert_isCloseToPercentage_int_Test.java
- src/test/java/org/assertj/core/api/integer_/IntegerAssert_isCloseTo_int_Test.java
- src/test/java/org/assertj/core/api/integer_/IntegerAssert_isEqualTo_noncastable_long_Test.java
- src/test/java/org/assertj/core/api/integer_/IntegerAssert_isNotCloseToPercentage_int_Test.java
- src/test/java/org/assertj/core/api/integer_/IntegerAssert_isNotCloseTo_int_Test.java
> Increase AbstractIntegerAssert test coverage to 100%

- src/main/java/org/assertj/core/api/AbstractMatcherAssert.java
- src/main/java/org/assertj/core/api/Assertions.java
- src/main/java/org/assertj/core/api/AssertionsForClassTypes.java
- src/main/java/org/assertj/core/api/Assumptions.java
- src/main/java/org/assertj/core/api/BDDAssertions.java
- src/main/java/org/assertj/core/api/BDDAssumptions.java
- src/main/java/org/assertj/core/api/BDDSoftAssertionsProvider.java
- src/main/java/org/assertj/core/api/InstanceOfAssertFactories.java
- src/main/java/org/assertj/core/api/MatcherAssert.java
- src/main/java/org/assertj/core/api/StandardSoftAssertionsProvider.java
- src/main/java/org/assertj/core/api/WithAssertions.java
- src/main/java/org/assertj/core/api/WithAssumptions.java
- src/main/java/org/assertj/core/error/MatcherShouldMatch.java
- src/test/java/org/assertj/core/api/matcher/MatcherAssert_matches_Test.java
- src/test/java/org/assertj/core/error/MatcherShouldMatch_create_Test.java
> implement matches() in #2081

- src/main/java/org/assertj/core/internal/Maps.java
- src/test/java/org/assertj/core/internal/maps/Maps_assertContainsOnlyKeys_Test.java
- src/test/java/org/assertj/core/internal/maps/Maps_assertContainsOnly_Test.java
* Fixes #2547
* Javadoc with a code example (on API only) : N/A
> Avoid cloning `MultiValueMapAdapter` instances

- src/main/java/org/assertj/core/api/AbstractLocalDateAssert.java
- src/test/java/org/assertj/core/api/localdate/LocalDateAsset_hasDayOfMonth_Test.java
* Fixes #[2541](https://github.com/assertj/assertj-core/issues/2541)  hasDayOfMonth task
> 2541 has day of month

- src/main/java/org/assertj/core/api/AbstractLocalDateTimeAssert.java
- src/test/java/org/assertj/core/api/localdatetime/LocalDateTimeAssert_hasNano_Test.java
> Adding has nano

- .mvn/wrapper/MavenWrapperDownloader.java
- .mvn/wrapper/maven-wrapper.properties
- mvnw
- mvnw.cmd
keeping build config up to date
> [mvn] Update maven wrapper to 3.1.1

- CONTRIBUTING.md
- README.md
- pom.xml
> Fix some typos and grammar in project documentation

- src/test/java/org/assertj/core/api/assumptions/BDDAssumptionsTest.java
Just a quick one while I remember. Spotted a BDD assumption test that was not doing anything.
> Fix incomplete test for given(Duration) in BDDAssumptionsTest

- src/main/java/org/assertj/core/internal/Strings.java
- src/test/java/org/assertj/core/internal/strings/Strings_assertContainsIgnoringCase_Test.java
- src/test/java/org/assertj/core/internal/strings/Strings_assertDoesNotContainIgnoringCase_Test.java
- src/test/java/org/assertj/core/internal/strings/Strings_assertDoesNotEndWithIgnoringCase_Test.java
- src/test/java/org/assertj/core/internal/strings/Strings_assertDoesNotStartWithIgnoringCase_Test.java
- src/test/java/org/assertj/core/internal/strings/Strings_assertEndsWithIgnoringCase_Test.java
- src/test/java/org/assertj/core/internal/strings/Strings_assertEqualsIgnoringCase_Test.java
- src/test/java/org/assertj/core/internal/strings/Strings_assertNotEqualsIgnoringCase_Test.java
- src/test/java/org/assertj/core/internal/strings/Strings_assertStartsWithIgnoringCase_Test.java
- src/test/java/org/assertj/core/test/CaseInsensitiveStringComparatorTest.java
> Fix locale handling for ignoring case assertions

- assertj-core/src/main/java/org/assertj/core/condition/NestableCondition.java
- assertj-core/src/test/java/org/assertj/core/condition/NestableConditionFixtures.java
- assertj-core/src/test/java/org/assertj/core/condition/NestableCondition_assertionMessage_Test.java
- assertj-core/src/test/java/org/assertj/core/condition/NestableCondition_matches_Test.java
Fix #2692
* Unit tests : YES / NO / NA
* Javadoc with a code example (on API only) : YES / NO / NA
> Add nestable condition with docs and tests.

- assertj-core/src/main/java/org/assertj/core/api/AbstractCharSequenceAssert.java
- assertj-core/src/main/java/org/assertj/core/error/ShouldBeASCII.java
- assertj-core/src/main/java/org/assertj/core/error/ShouldBeAlphabetic.java
- assertj-core/src/main/java/org/assertj/core/error/ShouldBeAlphanumeric.java
- assertj-core/src/main/java/org/assertj/core/error/ShouldBeHexadecimal.java
- assertj-core/src/main/java/org/assertj/core/error/ShouldBePrintable.java
- assertj-core/src/main/java/org/assertj/core/error/ShouldBeVisible.java
- assertj-core/src/main/java/org/assertj/core/internal/Strings.java
- assertj-core/src/test/java/org/assertj/core/api/charsequence/CharSequenceAssert_isASCII_Test.java
- assertj-core/src/test/java/org/assertj/core/api/charsequence/CharSequenceAssert_isAlphabetic_Test.java
- assertj-core/src/test/java/org/assertj/core/api/charsequence/CharSequenceAssert_isAlphanumeric_Test.java
- assertj-core/src/test/java/org/assertj/core/api/charsequence/CharSequenceAssert_isHexadecimal_Test.java
- assertj-core/src/test/java/org/assertj/core/api/charsequence/CharSequenceAssert_isPrintable_Test.java
- assertj-core/src/test/java/org/assertj/core/api/charsequence/CharSequenceAssert_isVisible_Test.java
- assertj-core/src/test/java/org/assertj/core/error/ShouldBeASCII_create_Test.java
- assertj-core/src/test/java/org/assertj/core/error/ShouldBeAlphabetic_create_Test.java
- assertj-core/src/test/java/org/assertj/core/error/ShouldBeAlphanumeric_create_Test.java
- assertj-core/src/test/java/org/assertj/core/error/ShouldBeHexadecimal_create_Test.java
- assertj-core/src/test/java/org/assertj/core/error/ShouldBePrintable_create_Test.java
- assertj-core/src/test/java/org/assertj/core/error/ShouldBeVisible_create_Test.java
* Fixes #2472
* Unit tests : YES / NO / NA
* Javadoc with a code example (on API only) : YES / NO / NA
> Add additional assertions for `CharSequence`

- assertj-core/pom.xml
- assertj-parent/pom.xml
- assertj-tests/assertj-integration-tests/assertj-core-osgi/pom.xml
- assertj-tests/assertj-integration-tests/assertj-core-osgi/src/test/java/org/assertj/core/tests/osgi/AssumptionsTest.java
- assertj-tests/assertj-integration-tests/assertj-core-osgi/src/test/java/org/assertj/core/tests/osgi/SimpleTest.java
- assertj-tests/assertj-integration-tests/assertj-core-osgi/src/test/java/org/assertj/core/tests/osgi/soft/CustomSoftAssertionTest.java
- assertj-tests/assertj-integration-tests/assertj-core-osgi/verify.bndrun
- assertj-tests/assertj-integration-tests/assertj-core-testng-with-junit4/pom.xml
- assertj-tests/assertj-integration-tests/pom.xml
- assertj-tests/pom.xml
Related to step 1 of https://github.com/assertj/assertj/issues/2424#issuecomment-1202145883
> Move OSGi integration tests into separate module

- assertj-tests/assertj-performance-tests/pom.xml
- assertj-tests/assertj-performance-tests/src/test/java/org/assertj/core/tests/perf/ContainsOnlyPerfTest.java
- assertj-tests/assertj-performance-tests/src/test/java/org/assertj/core/tests/perf/SoftAssertionsPerfTest.java
- assertj-tests/assertj-performance-tests/src/test/java/org/assertj/core/tests/perf/TypeComparatorsPerfTest.java
- assertj-tests/pom.xml
Related to step 1 of https://github.com/assertj/assertj/issues/2424#issuecomment-1202145883
> Move performance tests into separate module

- assertj-tests/assertj-integration-tests/assertj-core-groovy/pom.xml
- assertj-tests/assertj-integration-tests/assertj-core-groovy/src/test/groovy/org/assertj/core/tests/groovy/Assertions_assertThat_with_Groovy_strings.groovy
- assertj-tests/assertj-integration-tests/pom.xml
> Add integration test infrastructure for Groovy

- assertj-parent/pom.xml
- pom.xml
> Promote release-related configuration to the root POM

- assertj-core/src/main/java/org/assertj/core/api/Assertions.java
- assertj-core/src/main/java/org/assertj/core/api/BDDAssertions.java
- assertj-core/src/main/java/org/assertj/core/api/WithAssertions.java
> javadoc correction for within(long, java.time.temporal.TemporalUnit)

- .github/workflows/cross-version.yml
- .github/workflows/main.yml
* Updates `EnricoMi/publish-unit-test-result-action` to v2;
* Fixes files pattern to publish JUnit test results
* Updates workflows to prevent double execution from PR (as `push` and `pull-request`)
> Fix test results summary

- .gitignore
- assertj-bom/pom.xml
- pom.xml
> Add Bill of Materials

- assertj-core/src/main/java/org/assertj/core/api/AbstractDateAssert.java
* Fixes Incorrect documentation / Javadoc
> Correcting bug in documentation

- assertj-core/src/main/java/org/assertj/core/api/AbstractCharSequenceAssert.java
> Removed unintentional @Deprecated from containsOnlyDigits() (#2908)

- assertj-core/src/main/java/org/assertj/core/api/AbstractClassAssert.java
- assertj-core/src/main/java/org/assertj/core/error/ShouldHaveNoPackage.java
- assertj-core/src/test/java/org/assertj/core/api/classes/ClassAssert_hasNoPackage_Test.java
- assertj-core/src/test/java/org/assertj/core/error/ShouldHaveNoPackage_create_Test.java
> Add `hasNoPackage` to `Class` assertions

- assertj-core/src/main/java/org/assertj/core/api/Assertions.java
- assertj-core/src/main/java/org/assertj/core/api/BDDAssertions.java
- assertj-core/src/main/java/org/assertj/core/api/ThrowingConsumer.java
- assertj-core/src/main/java/org/assertj/core/api/WithAssertions.java
- assertj-core/src/test/java/org/assertj/core/api/Assertions_allOf_with_ThrowingConsumer_Test.java
- assertj-core/src/test/java/org/assertj/core/api/Assertions_anyOf_with_ThrowingConsumer_Test.java
- assertj-core/src/test/java/org/assertj/core/api/Assertions_sync_with_BDDAssertions_WithAssertions_and_soft_assertions_variants_Test.java
> Add `anyOf(ThrowingConsumer...)` and `allOf(ThrowingConsumer...)`

- assertj-core/src/main/java/org/assertj/core/api/AbstractCompletableFutureAssert.java
- assertj-core/src/main/java/org/assertj/core/api/AbstractFutureAssert.java
- assertj-core/src/main/java/org/assertj/core/api/BDDAssumptions.java
- assertj-core/src/main/java/org/assertj/core/api/Char2DArrayAssert.java
- assertj-core/src/main/java/org/assertj/core/api/Object2DArrayAssert.java
> Fix Javadoc typos

- assertj-bom/pom.xml
- assertj-core/pom.xml
- assertj-guava/pom.xml
- pom.xml
Fixes #3308.
<details>
<summary><code>assertj-core</code> diff</summary>
```diff
--- assertj-core-3.24.2-pom.xml	2023-12-26 16:58:58
+++ assertj-core-3.25.0-pom.xml	2023-12-26 17:05:57
@@ -2,527 +2,131 @@
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<modelVersion>4.0.0</modelVersion>
-    <parent>
-        <groupId>org.assertj</groupId>
-        <artifactId>assertj-parent</artifactId>
-        <version>3.24.2</version>
-        <relativePath>../assertj-parent</relativePath>
-    </parent>
+    <groupId>org.assertj</groupId>
<artifactId>assertj-core</artifactId>
+    <version>3.25.0-SNAPSHOT</version>
<name>AssertJ Core</name> …
```
> Apply `flatten-maven-plugin` to `assertj-core` and `assertj-guava`

- assertj-core/src/main/java/org/assertj/core/api/junit/jupiter/InjectSoftAssertions.java
> Fix typo in Javadoc

- assertj-core/src/main/java/org/assertj/core/api/InstanceOfAssertFactories.java
- assertj-core/src/test/java/org/assertj/core/api/Assertions_sync_with_InstanceOfAssertFactories_Test.java
- assertj-core/src/test/java/org/assertj/core/api/InstanceOfAssertFactoriesTest.java
- assertj-core/src/test/java/org/assertj/core/api/SoftAssertions_combined_with_asInstanceOf_Test.java
> Add `InstanceOfAssertFactory` for `Set` instances

- assertj-core/src/main/java/org/assertj/core/api/AbstractTemporalAssert.java
- assertj-core/src/main/java/org/assertj/core/api/Assertions.java
- assertj-core/src/main/java/org/assertj/core/api/Assumptions.java
- assertj-core/src/main/java/org/assertj/core/api/BDDAssertions.java
- assertj-core/src/main/java/org/assertj/core/api/BDDSoftAssertionsProvider.java
- assertj-core/src/main/java/org/assertj/core/api/InstanceOfAssertFactories.java
- assertj-core/src/main/java/org/assertj/core/api/StandardSoftAssertionsProvider.java
- assertj-core/src/main/java/org/assertj/core/api/WithAssertions.java
- assertj-core/src/test/java/org/assertj/core/api/AbstractTemporalAssert_isCloseTo_Test.java
- assertj-core/src/test/java/org/assertj/core/api/Assertions_assertThatTemporal_Test.java
- assertj-core/src/test/java/org/assertj/core/api/Assertions_assertThat_with_Comparable_Test.java
- assertj-core/src/test/java/org/assertj/core/api/Assertions_assertThat_with_LocalDateTime_Test.java
- assertj-core/src/test/java/org/assertj/core/api/Assertions_assertThat_with_LocalDate_Test.java
- assertj-core/src/test/java/org/assertj/core/api/Assertions_assertThat_with_OffsetDateTime_Test.java
- assertj-core/src/test/java/org/assertj/core/api/Assertions_assertThat_with_Temporal_Test.java
- assertj-core/src/test/java/org/assertj/core/api/Assertions_assertThat_with_YearMonth_Test.java
- assertj-core/src/test/java/org/assertj/core/api/Assertions_assertThat_with_ZonedDateTime_Test.java
- assertj-core/src/test/java/org/assertj/core/api/Assertions_sync_with_InstanceOfAssertFactories_Test.java
- assertj-core/src/test/java/org/assertj/core/api/SoftAssertionsTest.java
- assertj-core/src/test/java/org/assertj/core/api/assumptions/Assumptions_assumeThat_with_various_java_8_types_Test.java
This partially reverts 46630d711a0378067aaeaeb5899615647ccd2fdd.
Fixes #3491.
> Replace `assertThat(Temporal)` with `assertThatTemporal(Temporal)`

- .github/workflows/dependency-graph.yml
- .gitignore
- assertj-core/src/main/java/org/assertj/core/api/AbstractAssert.java
- assertj-tests/assertj-integration-tests/assertj-core-osgi/src/test/java/org/assertj/tests/core/osgi/AssumptionsTest.java
- assertj-tests/assertj-performance-tests/src/test/java/org/assertj/tests/core/perf/SoftAssertionsPerfTest.java
> Use java 21 in Dep graph & remove unused methods

- CONTRIBUTING.md
Small PR - Commit 3f3110fd56b2dc9b55ab8b4fb1a12b0fab439cef moved `AbstractCharSequenceAssert.java`. This PR adjusts sources to changes.
> Update `AbstractCharSequenceAssert.java` reference

- assertj-core/src/main/java/org/assertj/core/error/AssertJMultipleFailuresError.java
- assertj-core/src/main/java/org/assertj/core/error/ShouldHaveMethods.java
- assertj-core/src/main/java/org/assertj/core/groups/Properties.java
- assertj-core/src/main/java/org/assertj/core/internal/Arrays.java
- assertj-core/src/main/java/org/assertj/core/internal/Lists.java
- assertj-core/src/main/java/org/assertj/core/internal/Maps.java
- assertj-core/src/main/java/org/assertj/core/internal/Paths.java
- assertj-core/src/main/java/org/assertj/core/util/Strings.java
- assertj-core/src/test/java/org/assertj/core/api/AutoCloseableBDDSoftAssertionsTest.java
- assertj-core/src/test/java/org/assertj/core/api/BDDSoftAssertionsTest.java
- assertj-core/src/test/java/org/assertj/core/api/abstract_/AbstractAssert_isNotEqualTo_Test.java
- assertj-core/src/test/java/org/assertj/core/api/localdatetime/LocalDateTimeAssert_hasMinute_Test.java
- assertj-core/src/test/java/org/assertj/core/api/recursive/comparison/DualValueDequeTest.java
- assertj-core/src/test/java/org/assertj/core/util/DateUtil_format_with_date_time_format_Test.java
- assertj-core/src/test/java/org/assertj/core/util/DateUtil_toCalendar_Test.java
- assertj-tests/assertj-integration-tests/assertj-core-tests/src/test/java/org/assertj/tests/core/api/recursive/assertion/RecursiveAssertionDriver_OptionalPolicy_Test.java
- assertj-tests/assertj-integration-tests/assertj-core-tests/src/test/java/org/assertj/tests/core/api/recursive/comparison/DualValueUtil.java
- assertj-tests/assertj-integration-tests/assertj-core-tests/src/test/java/org/assertj/tests/core/api/recursive/comparison/RecursiveComparisonAssert_isEqualTo_with_optional_Test.java
* Fixes n/a
---
* use capital `L` for long numbers
* use `isEmpty` on collection instead of `size() == 0` and `size() != 0` variants
* remove leading `0` from numbers to make them decimal, not octet
> Quality Improvements

- assertj-core/src/main/java/org/assertj/core/util/introspection/Introspection.java
- assertj-tests/assertj-integration-tests/assertj-core-tests/src/test/java/org/assertj/tests/core/api/recursive/comparison/RecursiveComparisonAssert_isNotEqualTo_with_record_Test.java
> Fix missing introspection for record accessors

- assertj-core/src/main/java/org/assertj/core/api/recursive/comparison/RecursiveComparisonDifferenceCalculator.java
- assertj-tests/assertj-integration-tests/assertj-core-tests/src/test/java/org/assertj/tests/core/api/recursive/comparison/RecursiveComparisonAssert_isEqualTo_ignoringFields_Test.java
* Forward port of #3723
* Fixes #3722
> Restore support for null-valued maps when ignoring fields

- .github/workflows/main.yml
> Add Kotlin cross-version job

- assertj-core/src/main/java/org/assertj/core/api/ClassLoadingStrategyFactory.java
Running into this locally - and of course it works in my IDE, but not CLI or build system, making adding a breakpoint to track down the class in question a pain.
> Add Class info to failure exception

- assertj-core/src/main/java/org/assertj/core/error/BasicErrorMessageFactory.java
- assertj-core/src/main/java/org/assertj/core/presentation/StandardRepresentation.java
- assertj-core/src/test/java/org/assertj/core/error/BasicErrorMessageFactory_unquotedString_Test.java
- assertj-tests/assertj-integration-tests/assertj-core-tests/src/test/java/org/assertj/tests/core/presentation/StandardRepresentation_toStringOf_Test.java
Fix #3733
* Unit tests : YES / NO / NA
* Javadoc with a code example (on API only) : YES / NO / NA
> Fix `StandardRepresentation` regression for unquoted strings

- .mvn/wrapper/maven-wrapper.properties
> Bump Maven from 3.9.9 to 3.9.10

- assertj-core/src/main/java/org/assertj/core/api/AbstractAssert.java
- assertj-core/src/main/java/org/assertj/core/api/AbstractSoftAssertions.java
- assertj-core/src/main/java/org/assertj/core/api/Assertions.java
- assertj-core/src/main/java/org/assertj/core/api/AssertionsForClassTypes.java
- assertj-core/src/main/java/org/assertj/core/api/BDDAssertions.java
- assertj-core/src/main/java/org/assertj/core/api/Fail.java
- assertj-core/src/main/java/org/assertj/core/api/Java6Assertions.java
- assertj-core/src/main/java/org/assertj/core/api/WithAssertions.java
- assertj-core/src/main/java/org/assertj/core/internal/annotation/Contract.java
> Annotate `fail` methods with custom `@Contract`

- .github/workflows/binary-compatibility.yml
- .github/workflows/codeql.yml
- .github/workflows/main.yml
- .github/workflows/release.yml
- CONTRIBUTING.md
- assertj-parent/pom.xml
- assertj-tests/pom.xml
- javadoc-theme/assertj-theme.css
- pom.xml
> Upgrade build to Java 25
